export const qk = {
  masterData: {
    all: ["masterData"] as const,
    currencies: (params: Record<string, unknown> = {}) => ["masterData", "currencies", params] as const,
    paymentTerms: (params: Record<string, unknown> = {}) => ["masterData", "paymentTerms", params] as const,
    incoterms: (params: Record<string, unknown> = {}) => ["masterData", "incoterms", params] as const,
    taxCodes: (params: Record<string, unknown> = {}) => ["masterData", "taxCodes", params] as const,
    departments: (params: Record<string, unknown> = {}) => ["masterData", "departments", params] as const,
    units: (params: Record<string, unknown> = {}) => ["masterData", "units", params] as const,
    commodityCodes: (params: Record<string, unknown> = {}) => ["masterData", "commodityCodes", params] as const,
  },
  suppliers: {
    all: ["suppliers"] as const,
    list: (params: Record<string, unknown> = {}) => ["suppliers", "list", params] as const,
    detail: (id: string | number) => ["suppliers", "detail", String(id)] as const,
    defaults: (id: string | number) => ["suppliers", "detail", String(id), "defaults"] as const,
    sites: (id: string | number) => ["suppliers", "detail", String(id), "sites"] as const,
  },
  contracts: {
    all: ["contracts"] as const,
    list: (params: Record<string, unknown> = {}) => ["contracts", "list", params] as const,
    detail: (id: string | number) => ["contracts", "detail", String(id)] as const,
    revisions: (id: string | number) => ["contracts", "detail", String(id), "revisions"] as const,
  },
  requisitions: {
    all: ["requisitions"] as const,
    list: (params: Record<string, unknown> = {}) => ["requisitions", "list", params] as const,
    detail: (id: string | number) => ["requisitions", "detail", String(id)] as const,
  },
  purchaseOrders: {
    all: ["purchaseOrders"] as const,
    list: (params: Record<string, unknown> = {}) => ["purchaseOrders", "list", params] as const,
    envelope: (params: Record<string, unknown> = {}) => ["purchaseOrders", "envelope", params] as const,
    records: (params: Record<string, unknown> = {}) => ["purchaseOrders", "records", params] as const,
    detail: (po: string | number) => ["purchaseOrders", "detail", String(po)] as const,
    revisions: (id: string | number) => ["purchaseOrders", "detail", String(id), "revisions"] as const,
    commercialTerms: (po: string | number) => ["purchaseOrders", "detail", String(po), "commercialTerms"] as const,
  },
  inventory: { all: ["inventory"] as const, list: (p: Record<string, unknown> = {}) => ["inventory", "list", p] as const, stats: (p: Record<string, unknown> = {}) => ["inventory", "stats", p] as const },
  invoices: { all: ["invoices"] as const, list: (p: Record<string, unknown> = {}) => ["invoices", "list", p] as const, detail: (id: string|number)=>["invoices","detail",String(id)] as const, lines:(id:string|number)=>["invoices","detail",String(id),"lines"] as const},
  ap: { all:["ap"] as const, overview:(p:Record<string,unknown>={})=>["ap","overview",p] as const, paymentBatches:(p:Record<string,unknown>={})=>["ap","paymentBatches",p] as const },
  logistics: { all:["logistics"] as const, shipments:(p:Record<string,unknown>={})=>["logistics","shipments",p] as const, overview:(p:Record<string,unknown>={})=>["logistics","overview",p] as const },
  controlTower: { all:["controlTower"] as const, overview:(p:Record<string,unknown>={})=>["controlTower","overview",p] as const },
  analytics: { all:["analytics"] as const, overview:(p:Record<string,unknown>={})=>["analytics","overview",p] as const, reports:(rk:string,p:Record<string,unknown>={})=>["analytics","reports",rk,p] as const },
  reports: { all:["reports"] as const, report:(rk:string,p:Record<string,unknown>={})=>["reports",rk,p] as const },
  notifications: { all:["notifications"] as const, list:(p:Record<string,unknown>={})=>["notifications","list",p] as const },
};
