import type { TutorialStep } from "@/components/tutorial/tutorial-types";
import { APP_ROUTES } from "@/lib/routes/app-routes";

/** Cross-app guided tour from Control Tower — navigates and uses spotlight + row click. */
export const FULL_APP_TOUR_STEPS: TutorialStep[] = [
  {
    id: "tour-dashboard",
    title: "Your command center",
    text: "KPIs summarize open exceptions, late shipments, POs awaiting action, and low-stock SKUs. Each card deep-links into the right workspace. The badge shows database/schema readiness.",
    route: "/",
    routeExact: true,
    presentation: "spotlight",
    attachTo: { element: "[data-tour=dashboard-summary]", on: "bottom" },
  },
  {
    id: "tour-inventory-search",
    title: "Find SKUs fast",
    text: "Search by SKU or name, filter by location and category, and toggle Low stock only. Export CSV or refresh when you need a snapshot for audits.",
    route: "/inventory",
    routeExact: true,
    presentation: "spotlight",
    attachTo: { element: "[data-tour=inventory-search]", on: "bottom" },
  },
  {
    id: "tour-inventory-table",
    title: "Drill into detail",
    text: "Each row opens the item timeline, positions, and Adjust stock. Click any row now — the next step appears on the detail screen.",
    route: "/inventory",
    routeExact: true,
    presentation: "spotlight",
    attachTo: { element: "[data-tour=inventory-table]", on: "top" },
    advanceOnTargetClick: true,
  },
  {
    id: "tour-inventory-detail",
    title: "On-hand vs allocated",
    text: "Quantities roll up here; positions break stock by location. Adjust stock posts movements and can raise exceptions when something looks wrong.",
    presentation: "spotlight",
    settleMs: 120,
    attachTo: { element: "[data-tour=inventory-detail-summary]", on: "bottom" },
  },
  {
    id: "tour-exceptions",
    title: "Resolve operational issues",
    text: "Filter by severity, status, and type; export CSV; run checks to generate fresh issues from rules. Rows open assignment, comments, and status changes.",
    route: "/exceptions",
    routeExact: true,
    presentation: "spotlight",
    attachTo: { element: "[data-tour=exceptions-list]", on: "top" },
  },
  {
    id: "tour-purchase",
    title: "Procure and receive",
    text: "Switch between Purchase Orders and Requisitions. Search POs, then open a row to approve, send, or receive lines into inventory.",
    route: "/purchase",
    routeExact: true,
    presentation: "spotlight",
    attachTo: { element: "[data-tour=po-list]", on: "top" },
  },
  {
    id: "tour-shipments",
    title: "Logistics rhythm",
    text: "Track shipments by status, PO, carrier, and risk. Managers can add shipments tied to PO numbers to keep inbound visible.",
    route: "/logistics",
    routeExact: true,
    presentation: "spotlight",
    attachTo: { element: "[data-tour=shipments-list]", on: "top" },
  },
  {
    id: "tour-integrations",
    title: "Automate sync",
    text: "Run ERP/WMS/TMS connectors on demand and read the run log for timestamps, status, and messages.",
    route: "/integrations",
    routeExact: true,
    presentation: "spotlight",
    attachTo: { element: "[data-tour=integrations-runs]", on: "top" },
  },
  {
    id: "tour-reports",
    title: "Export with filters",
    text: "Pick format (PDF, CSV, Excel…), tune PDF templates, and export the active tab with the filters you set.",
    route: "/reports",
    routeExact: true,
    presentation: "spotlight",
    attachTo: { element: "[data-tour=reports-section]", on: "bottom" },
  },
  {
    id: "tour-complete",
    title: "You are set",
    text: "Re-run demos from Overview, reset data under Settings → Development Utilities when you want a clean slate, or keep exploring with the per-page tours from the help menu.",
    route: "/",
    routeExact: true,
    presentation: "spotlight",
    attachTo: { element: "[data-tour=system-status]", on: "left" },
  },
];

export const PAGE_TOUR_DEFINITIONS: Record<string, TutorialStep[]> = {
  "page-control-tower": [
    {
      id: "pct-kpis",
      title: "Operational KPIs",
      text: "These tiles summarize risk across logistics, purchasing, and inventory without leaving the tower view.",
      route: "/control-tower",
      routeExact: true,
      presentation: "spotlight",
      attachTo: { element: "[data-tour=control-tower-kpis]", on: "bottom" },
    },
    {
      id: "pct-links",
      title: "Jump to work",
      text: "Use the shortcuts to open Exceptions, Shipments, or Purchase Orders in full workspace pages.",
      route: "/control-tower",
      routeExact: true,
      presentation: "spotlight",
      attachTo: { element: "[data-tour=control-tower-shortcuts]", on: "bottom" },
    },
  ],
  "page-home": [
    {
      id: "ph-kpis",
      title: "KPI deep links",
      text: "These four tiles are your fastest path into Exceptions, Logistics, Purchase, and filtered Inventory.",
      route: "/",
      routeExact: true,
      presentation: "spotlight",
      attachTo: { element: "[data-tour=dashboard-summary]", on: "bottom" },
    },
    {
      id: "ph-actions",
      title: "Tutorial & demo",
      text: "Start the full guided tour anytime, or run the demo walkthrough to reseed data (this clears your session).",
      route: "/",
      routeExact: true,
      presentation: "spotlight",
      attachTo: { element: "[data-tour=control-tower-actions]", on: "bottom" },
    },
    {
      id: "ph-health",
      title: "Live readiness",
      text: "The system badge reflects database + schema checks so you know if you are in live or degraded mode.",
      route: "/",
      routeExact: true,
      presentation: "spotlight",
      attachTo: { element: "[data-tour=system-status]", on: "left" },
    },
  ],
  "page-inventory": [
    {
      id: "pi-search",
      title: "Search & scope",
      text: "Narrow the list before you act — operations teams live in these filters.",
      route: "/inventory",
      routeExact: true,
      presentation: "spotlight",
      attachTo: { element: "[data-tour=inventory-search]", on: "bottom" },
    },
    {
      id: "pi-signal",
      title: "Low-stock lens",
      text: "Toggle this to focus on SKUs that need replenishment or follow-up.",
      route: "/inventory",
      routeExact: true,
      presentation: "spotlight",
      attachTo: { element: "[data-tour=inventory-low-toggle]", on: "left" },
    },
    {
      id: "pi-grid",
      title: "Operational table",
      text: "Click through to detail for movements, positions, and adjustments.",
      route: "/inventory",
      routeExact: true,
      presentation: "spotlight",
      attachTo: { element: "[data-tour=inventory-table]", on: "top" },
      advanceOnTargetClick: true,
    },
  ],
  "page-inventory-detail": [
    {
      id: "pid-summary",
      title: "Quantity story",
      text: "Compare on-hand, allocated, and available before you trust a net count.",
      presentation: "spotlight",
      attachTo: { element: "[data-tour=inventory-detail-summary]", on: "bottom" },
    },
    {
      id: "pid-positions",
      title: "Where it sits",
      text: "Bins and locations explain why totals differ across the network.",
      presentation: "spotlight",
      attachTo: { element: "[data-tour=inventory-positions]", on: "top" },
    },
  ],
  "page-exceptions": [
    {
      id: "pex-scope",
      title: "Triage filters",
      text: "Pair free-text fields with the type preset to isolate the incidents you own.",
      route: "/exceptions",
      routeExact: true,
      presentation: "spotlight",
      attachTo: { element: "[data-tour=exceptions-toolbar]", on: "bottom" },
    },
    {
      id: "pex-grid",
      title: "Work the queue",
      text: "Open a row to comment, assign, and drive status transitions.",
      route: "/exceptions",
      routeExact: true,
      presentation: "spotlight",
      attachTo: { element: "[data-tour=exceptions-table]", on: "top" },
      advanceOnTargetClick: true,
    },
  ],
  "page-logistics": [
    {
      id: "pl-filters",
      title: "Shipment filters",
      text: "Status, PO, carrier, and late-risk views help dispatchers prioritize.",
      route: "/logistics",
      routeExact: true,
      presentation: "spotlight",
      attachTo: { element: "[data-tour=logistics-toolbar]", on: "bottom" },
    },
    {
      id: "pl-board",
      title: "Fleet table",
      text: "Click through for detail, proof of delivery notes, and activity.",
      route: "/logistics",
      routeExact: true,
      presentation: "spotlight",
      attachTo: { element: "[data-tour=shipments-list]", on: "top" },
      advanceOnTargetClick: true,
    },
  ],
  "page-purchase": [
    {
      id: "pp-tabs",
      title: "Two workflows",
      text: "Requisitions capture demand; purchase orders execute it. Jump between both without losing context.",
      route: "/purchase",
      routeExact: true,
      presentation: "spotlight",
      attachTo: { element: "[data-tour=purchase-tabs]", on: "bottom" },
    },
    {
      id: "pp-list",
      title: "PO operations",
      text: "Search, filter, then open a PO to approve, send, or receive inventory.",
      route: "/purchase",
      routeExact: true,
      presentation: "spotlight",
      attachTo: { element: "[data-tour=po-list]", on: "top" },
      advanceOnTargetClick: true,
    },
  ],
  "page-integrations": [
    {
      id: "pint-connectors",
      title: "Connectors",
      text: "Each card shows the latest status and lets you fire a run immediately.",
      route: "/integrations",
      routeExact: true,
      presentation: "spotlight",
      attachTo: { element: "[data-tour=integrations-connectors]", on: "bottom" },
    },
    {
      id: "pint-log",
      title: "Run log",
      text: "Audit who ran what, when it finished, and any error messages returned.",
      route: "/integrations",
      routeExact: true,
      presentation: "spotlight",
      attachTo: { element: "[data-tour=integrations-runs]", on: "top" },
    },
  ],
  "page-reports": [
    {
      id: "pr-export",
      title: "Export cockpit",
      text: "Choose the output format and PDF template before you generate a file.",
      route: "/reports",
      routeExact: true,
      presentation: "spotlight",
      attachTo: { element: "[data-tour=reports-section]", on: "bottom" },
    },
    {
      id: "pr-tabs",
      title: "Report families",
      text: "Swap tabs to change the dataset — inventory, low stock, POs, suppliers, and more.",
      route: "/reports",
      routeExact: true,
      presentation: "spotlight",
      attachTo: { element: "[data-tour=reports-tabs]", on: "bottom" },
    },
  ],
  "page-documents": [
    {
      id: "pdoc-upload",
      title: "Attach with context",
      text: "Pick the entity type and ID, choose a file, then walk through the upload checklist dialog.",
      route: "/documents",
      routeExact: true,
      presentation: "spotlight",
      attachTo: { element: "[data-tour=documents-upload]", on: "bottom" },
    },
    {
      id: "pdoc-library",
      title: "Document library",
      text: "Filter the grid to audit versions across POs, suppliers, invoices, and warehouses.",
      route: "/documents",
      routeExact: true,
      presentation: "spotlight",
      attachTo: { element: "[data-tour=documents-library]", on: "top" },
    },
  ],
  "page-supply-analytics": [
    {
      id: "psa-insights",
      title: "Rule-based insights",
      text: "These cards interpret KPIs locally — great for standups before you add heavier ML later.",
      route: "/analytics/procurement",
      routeExact: true,
      presentation: "spotlight",
      attachTo: { element: "[data-tour=supply-insights]", on: "bottom" },
    },
    {
      id: "psa-filters",
      title: "Slice spend analytics",
      text: "Apply dates and department filters, then hit Apply to refresh spend + turnover tiles.",
      route: "/analytics/procurement",
      routeExact: true,
      presentation: "spotlight",
      attachTo: { element: "[data-tour=supply-filters]", on: "top" },
    },
    {
      id: "psa-expiring",
      title: "Expiry horizon",
      text: "Watch SKUs approaching expiry so planners can intervene before waste hits.",
      route: "/analytics/procurement",
      routeExact: true,
      presentation: "spotlight",
      attachTo: { element: "[data-tour=supply-expiring]", on: "top" },
    },
  ],
  "page-suppliers": [
    {
      id: "psu-list",
      title: "Supplier roster",
      text: "Select a card to edit contacts, compliance, performance, and logos.",
      route: "/suppliers",
      routeExact: true,
      presentation: "spotlight",
      attachTo: { element: "[data-tour=suppliers-list]", on: "top" },
    },
  ],
  "page-warehouses": [
    {
      id: "pwh-add",
      title: "Network growth",
      text: "Create warehouses when you onboard a new site — structure matters for movements.",
      route: "/warehouses",
      routeExact: true,
      presentation: "spotlight",
      attachTo: { element: "[data-tour=warehouses-actions]", on: "bottom" },
    },
    {
      id: "pwh-grid",
      title: "Location directory",
      text: "Review capacity, contacts, and drill into bin strategies per site.",
      route: "/warehouses",
      routeExact: true,
      presentation: "spotlight",
      attachTo: { element: "[data-tour=warehouses-table]", on: "top" },
    },
  ],
  "page-analytics": [
    {
      id: "pan-charts",
      title: "Inventory analytics",
      text: "This page mirrors classic BI views — value, demand, and custom graph builder live here.",
      route: "/analytics",
      routeExact: true,
      presentation: "spotlight",
      targetSelector: "#analytics",
    },
  ],
  "page-dashboard": [
    {
      id: "pdb-stats",
      title: "Analytics overview",
      text: "Quick stats and workspace entry live on the analytics overview — use Control Tower for day-to-day operations.",
      route: APP_ROUTES.analytics.overview,
      routeExact: true,
      presentation: "spotlight",
      targetSelector: "#dashboard-stats",
    },
  ],
  "page-settings": [
    {
      id: "pst-intro",
      title: "Workspace preferences",
      text: "Tune company profile, operational toggles, PDF templates, and developer utilities. Settings centralize branding and dangerous demo tools — explore each card deliberately.",
      route: "/settings",
      routeExact: true,
      presentation: "modal",
    },
  ],
  "page-users": [
    {
      id: "pus-intro",
      title: "Governance",
      text: "Map people to roles so approvals, warehouse actions, and admin tools stay compliant. Align responsibilities with the approval policies you configured elsewhere.",
      route: "/user-roles",
      routeExact: true,
      presentation: "modal",
    },
  ],
  "page-purchase-detail": [
    {
      id: "ppd-lines",
      title: "PO execution",
      text: "Lines show what you ordered; receiving updates inventory and can raise exceptions. Approve, send, and receive from this screen — revision history and approval policy panels explain how the PO evolved.",
      presentation: "modal",
    },
  ],
  "page-exception-detail": [
    {
      id: "ped-work",
      title: "Exception workspace",
      text: "Assign owners, capture comments, and move status forward with audit-friendly notes. Detail view is where exceptions leave the queue — keep stakeholders aligned.",
      presentation: "modal",
    },
  ],
  "page-logistics-detail": [
    {
      id: "pld-work",
      title: "Shipment detail",
      text: "Update ETA, tracking, and proof-of-delivery metadata as carriers report in. Use this screen to align purchasing and warehouse teams on inbound timing.",
      presentation: "modal",
    },
  ],
};
