import {useQuery} from "@tanstack/react-query";
import {requestJson} from "@/lib/queryClient";
import {PageHeader} from "@/components/page-header";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {Tabs,TabsContent,TabsList,TabsTrigger} from "@/components/ui/tabs";
import {Button} from "@/components/ui/button";
const unwrap=(x:any)=>x?.data??x;
function Panel({query,empty,children}:{query:any;empty:string;children:(items:any[])=>React.ReactNode}){if(query.isLoading)return <p aria-live="polite">Loading receivables…</p>;if(query.isError)return <div className="space-y-2"><p>Receivables could not be loaded.</p><Button onClick={()=>query.refetch()}>Retry</Button></div>;const items=query.data?.items??[];return items.length?<>{children(items)}</>:<p>{empty}</p>}
export default function AccountsReceivablePage(){const customers=useQuery({queryKey:["ar-customers"],queryFn:async()=>unwrap(await requestJson("GET","/api/v2/finance/ar/customers?page=1&pageSize=25"))});const invoices=useQuery({queryKey:["ar-invoices"],queryFn:async()=>unwrap(await requestJson("GET","/api/v2/finance/ar/invoices?page=1&pageSize=25"))});const aging=useQuery({queryKey:["ar-aging"],queryFn:async()=>unwrap(await requestJson("GET","/api/v2/finance/ar/aging"))});return <div className="mx-auto max-w-7xl space-y-6 p-4 md:p-6"><PageHeader title="Accounts receivable" subtitle="Customer credit, receivables invoices, balances, and aging."/><Tabs defaultValue="customers"><TabsList className="flex h-auto flex-wrap"><TabsTrigger value="customers">Customers</TabsTrigger><TabsTrigger value="invoices">Invoices</TabsTrigger><TabsTrigger value="aging">Aging</TabsTrigger></TabsList><TabsContent value="customers"><Card><CardHeader><CardTitle>Customer balances</CardTitle></CardHeader><CardContent><Panel query={customers} empty="No customers configured.">{items=>items.map(x=><div key={x.id} className="grid grid-cols-[8rem_1fr_8rem_8rem] gap-3 border-b py-3"><strong>{x.customerNumber}</strong><span>{x.name}</span><span>{x.status}</span><span className="text-right">{x.currencyCode} {x.balance}</span></div>)}</Panel></CardContent></Card></TabsContent><TabsContent value="invoices"><Card><CardHeader><CardTitle>Receivables invoices</CardTitle></CardHeader><CardContent><Panel query={invoices} empty="No receivables invoices recorded.">{items=>items.map(x=><div key={x.id} className="grid grid-cols-[9rem_1fr_7rem_8rem_8rem] gap-3 border-b py-3"><strong>{x.invoiceNumber}</strong><span>{x.customerName}</span><span>{x.status}</span><span>{x.dueDate}</span><span className="text-right">{x.currencyCode} {x.balanceAmount}</span></div>)}</Panel></CardContent></Card></TabsContent><TabsContent value="aging"><Card><CardHeader><CardTitle>Receivables aging</CardTitle></CardHeader><CardContent><Panel query={aging} empty="No open receivables to age.">{items=>items.map(x=><div key={x.customerId} className="grid grid-cols-[1fr_repeat(5,7rem)] gap-3 border-b py-3"><strong>{x.customerName}</strong><span>{x.current}</span><span>{x.days1to30}</span><span>{x.days31to60}</span><span>{x.days61to90}</span><span>{x.days90Plus}</span></div>)}</Panel></CardContent></Card></TabsContent></Tabs></div>}
