import {useQuery} from "@tanstack/react-query";
import {requestJson} from "@/lib/queryClient";
import {PageHeader} from "@/components/page-header";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {Tabs,TabsContent,TabsList,TabsTrigger} from "@/components/ui/tabs";
import {Button} from "@/components/ui/button";
const unwrap=(v:any)=>v?.data??v;
function State({q,children}:{q:any;children:React.ReactNode}){if(q.isLoading)return <p>Loading financial records…</p>;if(q.isError)return <div><p>Financial records could not be loaded.</p><Button onClick={()=>q.refetch()}>Retry</Button></div>;return <>{children}</>}
export default function GeneralLedgerPage(){const accounts=useQuery({queryKey:["finance-accounts"],queryFn:async()=>unwrap(await requestJson("GET","/api/v2/finance/accounts?page=1&pageSize=100"))});const periods=useQuery({queryKey:["finance-periods"],queryFn:async()=>unwrap(await requestJson("GET","/api/v2/finance/periods"))});const journals=useQuery({queryKey:["finance-journals"],queryFn:async()=>unwrap(await requestJson("GET","/api/v2/finance/journals?page=1&pageSize=25"))});const trial=useQuery({queryKey:["finance-trial"],queryFn:async()=>unwrap(await requestJson("GET","/api/v2/finance/trial-balance"))});return <div className="mx-auto max-w-7xl space-y-6 p-4 md:p-6"><PageHeader title="General ledger" subtitle="Authoritative accounts, fiscal periods, posted journals, and trial balance."/><Tabs defaultValue="accounts"><TabsList className="flex h-auto flex-wrap"><TabsTrigger value="accounts">Chart of accounts</TabsTrigger><TabsTrigger value="periods">Fiscal periods</TabsTrigger><TabsTrigger value="journals">Journals</TabsTrigger><TabsTrigger value="trial">Trial balance</TabsTrigger></TabsList><TabsContent value="accounts"><Card><CardHeader><CardTitle>Chart of accounts</CardTitle></CardHeader><CardContent><State q={accounts}>{accounts.data?.items?.length?accounts.data.items.map((x:any)=><div key={x.id} className="grid grid-cols-[8rem_1fr_8rem] gap-3 border-b py-3"><strong>{x.code}</strong><span>{x.name}</span><span>{x.accountType}</span></div>):<p>No accounts configured.</p>}</State></CardContent></Card></TabsContent><TabsContent value="periods"><Card><CardHeader><CardTitle>Fiscal periods</CardTitle></CardHeader><CardContent><State q={periods}>{periods.data?.items?.map((x:any)=><div key={x.id} className="flex justify-between border-b py-3"><span>{x.name}: {x.startDate} – {x.endDate}</span><strong>{x.status}</strong></div>)}</State></CardContent></Card></TabsContent><TabsContent value="journals"><Card><CardHeader><CardTitle>Posted journals</CardTitle></CardHeader><CardContent><State q={journals}>{journals.data?.items?.map((x:any)=><div key={x.id} className="grid grid-cols-4 gap-3 border-b py-3"><strong>{x.entryNumber}</strong><span>{x.entryDate}</span><span>{x.description}</span><span className="text-right">{x.debitTotal} / {x.creditTotal}</span></div>)}</State></CardContent></Card></TabsContent><TabsContent value="trial"><Card><CardHeader><CardTitle>Trial balance</CardTitle></CardHeader><CardContent><State q={trial}>{trial.data?.items?.map((x:any)=><div key={x.id} className="grid grid-cols-[7rem_1fr_8rem_8rem_8rem] gap-3 border-b py-2"><strong>{x.code}</strong><span>{x.name}</span><span>{x.debit}</span><span>{x.credit}</span><span>{x.balance}</span></div>)}</State></CardContent></Card></TabsContent></Tabs></div>}
