import { useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { Link } from "wouter";
import { PageHeader } from "@/components/page-header";
import { PageDataState } from "@/components/page-shell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { queryClient, requestJson } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import { APP_ROUTES } from "@/lib/routes/app-routes";

type Page<T> = { items: T[]; total: number; page: number; pageSize: number; hasNext: boolean };
type Receipt = { id: number; receiptNumber: string; purchaseOrderId: number; purchaseOrderNumber: string; supplierName?: string; status: string; receivedDate: string; lineCount: number; acceptedQuantity: string; rejectedQuantity: string; reversed: boolean };
type ReturnRow = { id: number; returnNumber: string; purchaseOrderNumber: string; supplierName: string; warehouseName: string; status: string; reason: string; quantity: string; createdAt: string };
type ReceiptDetail = { receipt: { id: number; receipt_number: string; order_number: string; supplier_name?: string; status: string; received_date: string; notes?: string }; lines: Array<{ id: number; sku: string; item_name: string; quantity: string; accepted_quantity: string; rejected_quantity: string; ordered_quantity: string; received_quantity: string }>; reversals: Array<{ id: number; reason: string; created_at: string }> };
type ProcurementSettings = { phase2Enabled: boolean; phase4Enabled: boolean };

function Pager({ data, onPage }: { data: Page<unknown>; onPage: (page: number) => void }) {
  const first = data.total === 0 ? 0 : (data.page - 1) * data.pageSize + 1;
  const last = Math.min(data.page * data.pageSize, data.total);
  return <div className="flex flex-wrap items-center justify-between gap-3 border-t px-4 py-3 text-sm"><span className="text-muted-foreground">{first}–{last} of {data.total}</span><div className="flex gap-2"><Button size="sm" variant="outline" disabled={data.page <= 1} onClick={() => onPage(1)}>First</Button><Button size="sm" variant="outline" disabled={data.page <= 1} onClick={() => onPage(data.page - 1)}>Previous</Button><Button size="sm" variant="outline" disabled={!data.hasNext} onClick={() => onPage(data.page + 1)}>Next</Button><Button size="sm" variant="outline" disabled={!data.hasNext} onClick={() => onPage(Math.max(1, Math.ceil(data.total / data.pageSize)))}>Last</Button></div></div>;
}

export default function ProcurementReceivingPage() {
  const { toast } = useToast();
  const [selectedReceiptId, setSelectedReceiptId] = useState<number | null>(null);
  const [reversalReason, setReversalReason] = useState("");
  const [receiptPage, setReceiptPage] = useState(1);
  const [returnPage, setReturnPage] = useState(1);
  const settings = useQuery({ queryKey: ["/api/v2/procurement/settings"], queryFn: () => requestJson<ProcurementSettings>("GET", "/api/v2/procurement/settings") });
  const receipts = useQuery({ queryKey: ["/api/v2/procurement/receipts", receiptPage], queryFn: () => requestJson<Page<Receipt>>("GET", `/api/v2/procurement/receipts?page=${receiptPage}&pageSize=25`), placeholderData: (previous) => previous });
  const returns = useQuery({ queryKey: ["/api/v2/procurement/returns", returnPage], queryFn: () => requestJson<Page<ReturnRow>>("GET", `/api/v2/procurement/returns?page=${returnPage}&pageSize=25`), placeholderData: (previous) => previous });
  const detail = useQuery({ queryKey: ["/api/v2/procurement/receipts", selectedReceiptId], queryFn: () => requestJson<ReceiptDetail>("GET", `/api/v2/procurement/receipts/${selectedReceiptId}`), enabled: selectedReceiptId != null });
  const reverse = useMutation({ mutationFn: () => requestJson("POST", `/api/v2/procurement/receipts/${selectedReceiptId}/reverse`, { reason: reversalReason }, { headers: { "Idempotency-Key": `receipt-reversal-${selectedReceiptId}` } }), onSuccess: async () => { await Promise.all([queryClient.invalidateQueries({ queryKey: ["/api/v2/procurement/receipts"] }), detail.refetch()]); setReversalReason(""); toast({ title: "Goods receipt reversed", description: "Compensating inventory movements and immutable reversal evidence were created." }); }, onError: (error: Error) => toast({ title: "Reversal failed", description: error.message, variant: "destructive" }) });
  return <div className="space-y-6" data-testid="procurement-receiving-page"><PageHeader title="Receiving and returns" subtitle="Canonical goods receipts, discrepancies, inventory evidence, AP matching, reversals, and supplier returns." actions={<Button asChild><Link href={APP_ROUTES.operations.mobileReceive}>Open receive queue</Link></Button>} />
    {settings.data && (!settings.data.phase2Enabled || !settings.data.phase4Enabled) ? <div className="rounded-md border border-amber-300 bg-amber-50 p-3 text-sm text-amber-950" role="status">{!settings.data.phase2Enabled ? "Phase 2 is disabled: receipt reversals and contract receiving controls are read-only. " : ""}{!settings.data.phase4Enabled ? "Phase 4 is disabled: purchase returns and debit-note mutations are read-only." : ""} <Link className="font-medium underline" href={APP_ROUTES.procurement.settings}>Review procurement settings</Link></div> : null}
    <Tabs defaultValue="receipts"><TabsList><TabsTrigger value="receipts">Goods receipts</TabsTrigger><TabsTrigger value="returns">Purchase returns</TabsTrigger></TabsList>
      <TabsContent value="receipts"><PageDataState isLoading={receipts.isLoading} error={receipts.error} isEmpty={!receipts.data} emptyView={<div className="py-12 text-center text-muted-foreground">No posted goods receipts.</div>} onRetry={() => void receipts.refetch()}>{receipts.data ? <Card><CardHeader><CardTitle>{receipts.data.total} goods receipt{receipts.data.total === 1 ? "" : "s"}</CardTitle></CardHeader><CardContent className="overflow-x-auto p-0"><Table><TableHeader><TableRow><TableHead>GRN</TableHead><TableHead>PO / supplier</TableHead><TableHead>Received</TableHead><TableHead>Accepted / rejected</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Action</TableHead></TableRow></TableHeader><TableBody>{receipts.data.items.map((row) => <TableRow key={row.id} data-testid="receiving-row"><TableCell className="font-medium">{row.receiptNumber}</TableCell><TableCell><Link className="underline" href={APP_ROUTES.procurement.order(row.purchaseOrderNumber)}>{row.purchaseOrderNumber}</Link><div className="text-xs text-muted-foreground">{row.supplierName ?? "Supplier unavailable"}</div></TableCell><TableCell>{new Date(row.receivedDate).toLocaleDateString()}<div className="text-xs text-muted-foreground">{row.lineCount} line(s)</div></TableCell><TableCell>{row.acceptedQuantity} / {row.rejectedQuantity}</TableCell><TableCell><Badge variant={row.reversed ? "destructive" : "outline"}>{row.reversed ? "REVERSED" : row.status}</Badge></TableCell><TableCell className="text-right"><Button size="sm" variant="outline" onClick={() => setSelectedReceiptId(row.id)}>Review evidence</Button></TableCell></TableRow>)}{receipts.data.items.length === 0 ? <TableRow><TableCell colSpan={6} className="py-8 text-center text-muted-foreground">No posted goods receipts.</TableCell></TableRow> : null}</TableBody></Table><Pager data={receipts.data} onPage={setReceiptPage} /></CardContent></Card> : null}</PageDataState></TabsContent>
      <TabsContent value="returns"><PageDataState isLoading={returns.isLoading} error={returns.error} isEmpty={!returns.data} emptyView={<div className="py-12 text-center text-muted-foreground">No purchase returns.</div>} onRetry={() => void returns.refetch()}>{returns.data ? <Card><CardHeader><CardTitle>{returns.data.total} purchase return{returns.data.total === 1 ? "" : "s"}</CardTitle></CardHeader><CardContent className="overflow-x-auto p-0"><Table><TableHeader><TableRow><TableHead>Return</TableHead><TableHead>PO / supplier</TableHead><TableHead>Warehouse</TableHead><TableHead>Quantity</TableHead><TableHead>Status</TableHead><TableHead>Reason</TableHead></TableRow></TableHeader><TableBody>{returns.data.items.map((row) => <TableRow key={row.id}><TableCell className="font-medium">{row.returnNumber}</TableCell><TableCell>{row.purchaseOrderNumber}<div className="text-xs text-muted-foreground">{row.supplierName}</div></TableCell><TableCell>{row.warehouseName}</TableCell><TableCell>{row.quantity}</TableCell><TableCell><Badge variant="outline">{row.status}</Badge></TableCell><TableCell className="max-w-72 truncate" title={row.reason}>{row.reason}</TableCell></TableRow>)}{returns.data.items.length === 0 ? <TableRow><TableCell colSpan={6} className="py-8 text-center text-muted-foreground">No purchase returns. Create one from a posted receipt through the API-backed receipt detail workflow.</TableCell></TableRow> : null}</TableBody></Table><Pager data={returns.data} onPage={setReturnPage} /></CardContent></Card> : null}</PageDataState></TabsContent>
    </Tabs>
    <Dialog open={selectedReceiptId != null} onOpenChange={(open) => { if (!open) { setSelectedReceiptId(null); setReversalReason(""); } }}>
      <DialogContent className="max-h-[85vh] max-w-3xl overflow-y-auto">
        <DialogHeader><DialogTitle>Goods receipt evidence</DialogTitle><DialogDescription>Posted receipt, PO quantities, discrepancies, and immutable reversal history.</DialogDescription></DialogHeader>
        {detail.isLoading ? <div className="py-8 text-center text-muted-foreground">Loading receipt evidence…</div> : detail.error ? <div className="rounded-md border border-destructive/40 p-4 text-sm text-destructive">{detail.error.message}</div> : detail.data ? <div className="space-y-4">
          <div className="grid gap-3 rounded-md border p-4 sm:grid-cols-3"><div><p className="text-xs text-muted-foreground">GRN</p><p className="font-medium">{detail.data.receipt.receipt_number}</p></div><div><p className="text-xs text-muted-foreground">Purchase order</p><p className="font-medium">{detail.data.receipt.order_number}</p></div><div><p className="text-xs text-muted-foreground">Status</p><Badge variant="outline">{detail.data.receipt.status}</Badge></div></div>
          <div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Item</TableHead><TableHead>Receipt qty</TableHead><TableHead>Accepted</TableHead><TableHead>Rejected</TableHead></TableRow></TableHeader><TableBody>{detail.data.lines.map((line) => <TableRow key={line.id}><TableCell>{line.sku} · {line.item_name}</TableCell><TableCell>{line.quantity}</TableCell><TableCell>{line.accepted_quantity}</TableCell><TableCell>{line.rejected_quantity}</TableCell></TableRow>)}</TableBody></Table></div>
          {detail.data.reversals.length ? <div className="rounded-md border border-destructive/30 p-4"><p className="font-medium">Reversal history</p>{detail.data.reversals.map((item) => <p key={item.id} className="mt-2 text-sm">{new Date(item.created_at).toLocaleString()} · {item.reason}</p>)}</div> : <div className="space-y-2"><Label htmlFor="reversal-reason">Reversal reason</Label><Input id="reversal-reason" value={reversalReason} onChange={(event) => setReversalReason(event.target.value)} placeholder="Explain why a compensating receipt is required" /><p className="text-xs text-muted-foreground">Reversal never edits posted evidence. It creates compensating stock movements.</p></div>}
        </div> : null}
        <DialogFooter>{detail.data && detail.data.reversals.length === 0 ? <Button variant="destructive" disabled={!settings.data?.phase2Enabled || reversalReason.trim().length < 5 || reverse.isPending} onClick={() => reverse.mutate()}>{reverse.isPending ? "Reversing…" : settings.data?.phase2Enabled ? "Reverse receipt" : "Enable Phase 2 to reverse"}</Button> : null}</DialogFooter>
      </DialogContent>
    </Dialog>
  </div>;
}
