export type MdmRiskLevel = "low" | "medium" | "high" | "critical";

export type MdmDomainRegistryEntry = {
  key: string;
  displayName: string;
  ownerRole: string;
  stewardRole: string;
  riskLevel: MdmRiskLevel;
  requiredPermissions: string[];
  requiredFields: string[];
  uniqueKeys: string[];
  highRiskFields: string[];
  approvalRequiredFields: string[];
  whereUsedChecks: string[];
  supportedActions: Array<"read" | "create" | "update" | "deactivate" | "archive" | "import" | "export" | "approve">;
  importExportSupport: "none" | "export" | "import_export";
  auditRequired: boolean;
};

const baseActions: MdmDomainRegistryEntry["supportedActions"] = [
  "read",
  "create",
  "update",
  "deactivate",
  "archive",
  "export",
];

export const MDM_STANDARD_RECORD_FIELDS = [
  "organizationId",
  "code",
  "businessKey",
  "name",
  "status",
  "version",
  "effectiveFrom",
  "effectiveTo",
  "createdBy",
  "updatedBy",
  "approvedBy",
  "sourceSystem",
  "externalReference",
  "archivedAt",
  "archivedBy",
] as const;

export const HIGH_RISK_MDM_FIELDS = [
  "supplier.bankName",
  "supplier.accountNumberMasked",
  "supplier.taxNumber",
  "supplier.vatNumber",
  "glAccountCode",
  "costCentreId",
  "uomConversion.factor",
  "taxCode.rate",
  "paymentTerm.netDays",
  "contract.currency",
  "approvalRule.approverRole",
  "warehouse.active",
] as const;

function entry(input: MdmDomainRegistryEntry): MdmDomainRegistryEntry {
  return {
    ...input,
    auditRequired: true,
    supportedActions: input.supportedActions.length > 0 ? input.supportedActions : baseActions,
  };
}

export const MDM_DOMAIN_REGISTRY = [
  entry({
    key: "suppliers",
    displayName: "Suppliers",
    ownerRole: "procurement_manager",
    stewardRole: "supplier_master_steward",
    riskLevel: "critical",
    requiredPermissions: ["master-data:read", "suppliers:manage"],
    requiredFields: ["name", "supplierCode", "status", "defaultCurrencyCode", "paymentTermsId", "taxCodeId"],
    uniqueKeys: ["organizationId+supplierCode", "organizationId+taxNumber"],
    highRiskFields: ["bankName", "bankAccountNumber", "taxNumber", "status", "defaultCurrencyCode"],
    approvalRequiredFields: ["bankName", "bankAccountNumber", "taxNumber", "status"],
    whereUsedChecks: ["open requisitions", "open purchase orders", "AP invoices", "active contracts", "logistics"],
    supportedActions: [...baseActions, "import", "approve"],
    importExportSupport: "import_export",
    auditRequired: true,
  }),
  entry({
    key: "supplier-contacts",
    displayName: "Supplier Contacts",
    ownerRole: "procurement_manager",
    stewardRole: "supplier_master_steward",
    riskLevel: "medium",
    requiredPermissions: ["master-data:read", "suppliers:manage"],
    requiredFields: ["supplierId", "name", "contactType"],
    uniqueKeys: ["organizationId+supplierId+contactType+email"],
    highRiskFields: ["isPrimary", "email"],
    approvalRequiredFields: ["isPrimary"],
    whereUsedChecks: ["supplier communications", "PO distribution"],
    supportedActions: [...baseActions, "import"],
    importExportSupport: "import_export",
    auditRequired: true,
  }),
  entry({
    key: "supplier-banks",
    displayName: "Supplier Banks",
    ownerRole: "finance_manager",
    stewardRole: "ap_master_steward",
    riskLevel: "critical",
    requiredPermissions: ["master-data:read", "supplier-bank:manage"],
    requiredFields: ["supplierId", "bankName", "accountNumberMasked", "currencyCode", "verificationStatus"],
    uniqueKeys: ["organizationId+supplierId+bankName+accountNumberMasked"],
    highRiskFields: ["bankName", "accountNumberMasked", "swiftCode", "currencyCode", "isDefault"],
    approvalRequiredFields: ["bankName", "accountNumberMasked", "swiftCode", "isDefault"],
    whereUsedChecks: ["payment batches", "supplier payment defaults"],
    supportedActions: [...baseActions, "import", "approve"],
    importExportSupport: "import_export",
    auditRequired: true,
  }),
  entry({
    key: "supplier-compliance-documents",
    displayName: "Supplier Compliance Documents",
    ownerRole: "procurement_manager",
    stewardRole: "compliance_steward",
    riskLevel: "high",
    requiredPermissions: ["master-data:read", "suppliers:manage"],
    requiredFields: ["supplierId", "documentType", "status"],
    uniqueKeys: ["organizationId+supplierId+documentType+documentId"],
    highRiskFields: ["status", "expiryDate", "requiredForPo"],
    approvalRequiredFields: ["status", "requiredForPo"],
    whereUsedChecks: ["PO send compliance", "supplier onboarding"],
    supportedActions: [...baseActions, "import", "approve"],
    importExportSupport: "import_export",
    auditRequired: true,
  }),
  entry({
    key: "contracts",
    displayName: "Contracts",
    ownerRole: "procurement_manager",
    stewardRole: "contract_steward",
    riskLevel: "critical",
    requiredPermissions: ["master-data:read", "contracts:manage"],
    requiredFields: ["supplierId", "title", "startDate", "currency", "status"],
    uniqueKeys: ["organizationId+referenceNumber"],
    highRiskFields: ["currency", "paymentTermsId", "incotermId", "status", "value"],
    approvalRequiredFields: ["currency", "paymentTermsId", "status"],
    whereUsedChecks: ["purchase orders", "AP invoices", "supplier defaults"],
    supportedActions: [...baseActions, "import", "approve"],
    importExportSupport: "import_export",
    auditRequired: true,
  }),
  entry({
    key: "items",
    displayName: "Items / SKUs / Services",
    ownerRole: "inventory_manager",
    stewardRole: "item_master_steward",
    riskLevel: "high",
    requiredPermissions: ["master-data:read", "inventory:manage"],
    requiredFields: ["sku", "name", "unitOfMeasureId", "status", "price"],
    uniqueKeys: ["organizationId+sku"],
    highRiskFields: ["unitOfMeasureId", "taxCodeId", "glAccountCode", "status"],
    approvalRequiredFields: ["unitOfMeasureId", "glAccountCode", "status"],
    whereUsedChecks: ["open requisitions", "purchase orders", "warehouse stock", "reports"],
    supportedActions: [...baseActions, "import", "approve"],
    importExportSupport: "import_export",
    auditRequired: true,
  }),
  entry({
    key: "item-categories",
    displayName: "Item Categories",
    ownerRole: "inventory_manager",
    stewardRole: "item_master_steward",
    riskLevel: "high",
    requiredPermissions: ["master-data:read", "inventory:manage"],
    requiredFields: ["code", "name"],
    uniqueKeys: ["organizationId+code"],
    highRiskFields: ["defaultGlAccountCode", "defaultTaxCodeId", "active"],
    approvalRequiredFields: ["defaultGlAccountCode", "defaultTaxCodeId"],
    whereUsedChecks: ["items", "spend reports", "GL mappings"],
    supportedActions: [...baseActions, "import", "approve"],
    importExportSupport: "import_export",
    auditRequired: true,
  }),
  entry({
    key: "units-of-measure",
    displayName: "Units of Measure",
    ownerRole: "inventory_manager",
    stewardRole: "item_master_steward",
    riskLevel: "high",
    requiredPermissions: ["master-data:read", "inventory:manage"],
    requiredFields: ["code", "name"],
    uniqueKeys: ["code"],
    highRiskFields: ["code", "symbol", "active"],
    approvalRequiredFields: ["code", "active"],
    whereUsedChecks: ["items", "PO lines", "receipts", "stock counts"],
    supportedActions: [...baseActions, "import", "approve"],
    importExportSupport: "import_export",
    auditRequired: true,
  }),
  entry({
    key: "uom-conversions",
    displayName: "UOM Conversions",
    ownerRole: "inventory_manager",
    stewardRole: "item_master_steward",
    riskLevel: "critical",
    requiredPermissions: ["master-data:read", "inventory:manage"],
    requiredFields: ["fromUomId", "toUomId", "factor"],
    uniqueKeys: ["organizationId+fromUomId+toUomId+itemId"],
    highRiskFields: ["factor", "fromUomId", "toUomId", "itemId"],
    approvalRequiredFields: ["factor"],
    whereUsedChecks: ["open requisitions", "PO lines", "receipts"],
    supportedActions: [...baseActions, "import", "approve"],
    importExportSupport: "import_export",
    auditRequired: true,
  }),
  entry({
    key: "warehouses",
    displayName: "Warehouses",
    ownerRole: "warehouse_manager",
    stewardRole: "warehouse_master_steward",
    riskLevel: "high",
    requiredPermissions: ["master-data:read", "warehouses:manage"],
    requiredFields: ["name", "location", "active"],
    uniqueKeys: ["organizationId+name"],
    highRiskFields: ["active", "location", "contactPhone"],
    approvalRequiredFields: ["active"],
    whereUsedChecks: ["warehouse stock", "open receipts", "cycle counts", "transfers"],
    supportedActions: [...baseActions, "import", "approve"],
    importExportSupport: "import_export",
    auditRequired: true,
  }),
  entry({
    key: "bins-locations",
    displayName: "Bins / Locations",
    ownerRole: "warehouse_manager",
    stewardRole: "warehouse_master_steward",
    riskLevel: "medium",
    requiredPermissions: ["master-data:read", "warehouses:manage"],
    requiredFields: ["warehouseId", "code", "status"],
    uniqueKeys: ["organizationId+warehouseId+code"],
    highRiskFields: ["status", "capacity"],
    approvalRequiredFields: ["status"],
    whereUsedChecks: ["stock", "putaway", "cycle counts"],
    supportedActions: [...baseActions, "import"],
    importExportSupport: "import_export",
    auditRequired: true,
  }),
  entry({
    key: "departments",
    displayName: "Departments",
    ownerRole: "finance_manager",
    stewardRole: "org_master_steward",
    riskLevel: "high",
    requiredPermissions: ["master-data:read", "departments:manage"],
    requiredFields: ["code", "name"],
    uniqueKeys: ["organizationId+code"],
    highRiskFields: ["active", "costCenterId"],
    approvalRequiredFields: ["active", "costCenterId"],
    whereUsedChecks: ["open requisitions", "purchase orders", "reports"],
    supportedActions: [...baseActions, "import", "approve"],
    importExportSupport: "import_export",
    auditRequired: true,
  }),
  entry({
    key: "cost-centres",
    displayName: "Cost Centres",
    ownerRole: "finance_manager",
    stewardRole: "finance_master_steward",
    riskLevel: "critical",
    requiredPermissions: ["master-data:read", "finance-mapping:manage"],
    requiredFields: ["code", "name", "glAccountCode"],
    uniqueKeys: ["organizationId+code"],
    highRiskFields: ["glAccountCode", "departmentId", "active"],
    approvalRequiredFields: ["glAccountCode", "active"],
    whereUsedChecks: ["open requisitions", "PO lines", "AP invoices", "budgets"],
    supportedActions: [...baseActions, "import", "approve"],
    importExportSupport: "import_export",
    auditRequired: true,
  }),
  entry({
    key: "gl-accounts",
    displayName: "GL Accounts",
    ownerRole: "finance_manager",
    stewardRole: "finance_master_steward",
    riskLevel: "critical",
    requiredPermissions: ["master-data:read", "finance-mapping:manage"],
    requiredFields: ["code", "name", "accountType"],
    uniqueKeys: ["organizationId+code"],
    highRiskFields: ["code", "accountType", "active"],
    approvalRequiredFields: ["code", "active"],
    whereUsedChecks: ["GL mappings", "AP exports", "spend reports"],
    supportedActions: [...baseActions, "import", "approve"],
    importExportSupport: "import_export",
    auditRequired: true,
  }),
  entry({
    key: "tax-codes",
    displayName: "Tax Codes",
    ownerRole: "finance_manager",
    stewardRole: "tax_master_steward",
    riskLevel: "critical",
    requiredPermissions: ["master-data:read", "tax:manage"],
    requiredFields: ["code", "name", "rate", "type", "countryCode"],
    uniqueKeys: ["code"],
    highRiskFields: ["rate", "active", "countryCode"],
    approvalRequiredFields: ["rate", "active"],
    whereUsedChecks: ["suppliers", "POs", "AP invoices", "exports"],
    supportedActions: [...baseActions, "import", "approve"],
    importExportSupport: "import_export",
    auditRequired: true,
  }),
  entry({
    key: "currencies",
    displayName: "Currencies",
    ownerRole: "finance_manager",
    stewardRole: "treasury_master_steward",
    riskLevel: "high",
    requiredPermissions: ["master-data:read", "currencies:manage"],
    requiredFields: ["code", "name", "symbol", "exchangeRateToZar", "active"],
    uniqueKeys: ["code"],
    highRiskFields: ["exchangeRateToZar", "active", "isMainForRegion"],
    approvalRequiredFields: ["exchangeRateToZar", "active"],
    whereUsedChecks: ["suppliers", "contracts", "POs", "AP invoices", "reports"],
    supportedActions: [...baseActions, "import", "approve"],
    importExportSupport: "import_export",
    auditRequired: true,
  }),
  entry({
    key: "fx-rates",
    displayName: "FX Rates",
    ownerRole: "finance_manager",
    stewardRole: "treasury_master_steward",
    riskLevel: "critical",
    requiredPermissions: ["master-data:read", "currencies:manage"],
    requiredFields: ["fromCurrencyCode", "toCurrencyCode", "rate", "effectiveDate"],
    uniqueKeys: ["organizationId+fromCurrencyCode+toCurrencyCode+effectiveDate"],
    highRiskFields: ["rate", "manualOverrideAllowed", "expiresAt"],
    approvalRequiredFields: ["rate", "manualOverrideAllowed"],
    whereUsedChecks: ["PO approval values", "AP invoice matching", "reports"],
    supportedActions: [...baseActions, "import", "approve"],
    importExportSupport: "import_export",
    auditRequired: true,
  }),
  entry({
    key: "payment-terms",
    displayName: "Payment Terms",
    ownerRole: "finance_manager",
    stewardRole: "ap_master_steward",
    riskLevel: "high",
    requiredPermissions: ["master-data:read", "payment-terms:manage"],
    requiredFields: ["code", "name", "netDays"],
    uniqueKeys: ["code"],
    highRiskFields: ["netDays", "discountPercent", "active"],
    approvalRequiredFields: ["netDays", "discountPercent"],
    whereUsedChecks: ["suppliers", "contracts", "POs", "AP invoices"],
    supportedActions: [...baseActions, "import", "approve"],
    importExportSupport: "import_export",
    auditRequired: true,
  }),
  entry({
    key: "incoterms",
    displayName: "Incoterms",
    ownerRole: "procurement_manager",
    stewardRole: "supplier_master_steward",
    riskLevel: "medium",
    requiredPermissions: ["master-data:read", "incoterms:manage"],
    requiredFields: ["code", "description"],
    uniqueKeys: ["code"],
    highRiskFields: ["active"],
    approvalRequiredFields: ["active"],
    whereUsedChecks: ["suppliers", "contracts", "POs", "logistics"],
    supportedActions: [...baseActions, "import"],
    importExportSupport: "import_export",
    auditRequired: true,
  }),
  entry({
    key: "carriers",
    displayName: "Carriers",
    ownerRole: "logistics_manager",
    stewardRole: "logistics_master_steward",
    riskLevel: "medium",
    requiredPermissions: ["master-data:read", "carriers:manage"],
    requiredFields: ["code", "name"],
    uniqueKeys: ["organizationId+code"],
    highRiskFields: ["active", "contact"],
    approvalRequiredFields: ["active"],
    whereUsedChecks: ["suppliers", "shipments", "logistics analytics"],
    supportedActions: [...baseActions, "import"],
    importExportSupport: "import_export",
    auditRequired: true,
  }),
  entry({
    key: "approval-rules",
    displayName: "Approval Rules",
    ownerRole: "finance_manager",
    stewardRole: "governance_steward",
    riskLevel: "critical",
    requiredPermissions: ["master-data:read", "approval-policies:manage"],
    requiredFields: ["code", "name", "entityType", "approverRole", "approvalLevel"],
    uniqueKeys: ["organizationId+code"],
    highRiskFields: ["approverRole", "minLocalValue", "maxLocalValue", "active"],
    approvalRequiredFields: ["approverRole", "minLocalValue", "maxLocalValue"],
    whereUsedChecks: ["requisition approvals", "PO approvals", "AP approvals"],
    supportedActions: [...baseActions, "import", "approve"],
    importExportSupport: "import_export",
    auditRequired: true,
  }),
  entry({
    key: "document-sequences",
    displayName: "Document Sequences",
    ownerRole: "finance_manager",
    stewardRole: "document_control_steward",
    riskLevel: "high",
    requiredPermissions: ["master-data:read", "documents:manage"],
    requiredFields: ["documentType", "prefix", "nextNumber", "padding"],
    uniqueKeys: ["organizationId+documentType+prefix"],
    highRiskFields: ["nextNumber", "prefix", "active"],
    approvalRequiredFields: ["nextNumber", "prefix"],
    whereUsedChecks: ["requisitions", "purchase orders", "GRNs", "invoice batches"],
    supportedActions: [...baseActions, "import", "approve"],
    importExportSupport: "import_export",
    auditRequired: true,
  }),
  entry({
    key: "legal-entities",
    displayName: "Legal Entities / Company Profile",
    ownerRole: "admin",
    stewardRole: "company_profile_steward",
    riskLevel: "critical",
    requiredPermissions: ["master-data:read", "settings:manage"],
    requiredFields: ["code", "name", "defaultCurrencyCode", "countryCode"],
    uniqueKeys: ["organizationId+code"],
    highRiskFields: ["taxNumber", "registrationNumber", "defaultCurrencyCode", "active"],
    approvalRequiredFields: ["taxNumber", "defaultCurrencyCode", "active"],
    whereUsedChecks: ["document templates", "tax reporting", "purchase documents"],
    supportedActions: [...baseActions, "import", "approve"],
    importExportSupport: "import_export",
    auditRequired: true,
  }),
] as const satisfies readonly MdmDomainRegistryEntry[];

export function getMdmDomainRegistry() {
  return MDM_DOMAIN_REGISTRY;
}

export function getMdmDomainRegistryEntry(key: string) {
  return MDM_DOMAIN_REGISTRY.find((entry) => entry.key === key);
}

export function isHighRiskMdmField(domainKey: string, fieldName: string) {
  const entry = getMdmDomainRegistryEntry(domainKey);
  return Boolean(entry?.highRiskFields.includes(fieldName) || entry?.approvalRequiredFields.includes(fieldName));
}
