import { z } from "zod";

export const supplierFormSchema = z.object({
  name: z.string().min(2, "Supplier name must be at least 2 characters"),
  supplierCode: z.string().nullable().optional(),
  legalName: z.string().nullable().optional(),
  supplierType: z.enum(["goods", "service", "carrier", "contractor", "fuel"]).nullable().optional(),
  status: z.string().nullable().optional(),
  registrationNumber: z.string().nullable().optional(),
  category: z.string().nullable().optional(),
  contactName: z.string().nullable().optional(),
  financeContactName: z.string().nullable().optional(),
  logisticsContactName: z.string().nullable().optional(),
  email: z.string().email("Invalid email address").nullable().optional(),
  phone: z.string().nullable().optional(),
  address: z.string().nullable().optional(),
  billingAddress: z.string().nullable().optional(),
  remitToAddress: z.string().nullable().optional(),
  pickupSite: z.string().nullable().optional(),
  deliverySite: z.string().nullable().optional(),
  taxIdentificationNumber: z.string().nullable().optional(),
  bankName: z.string().nullable().optional(),
  bankAccountNumber: z.string().nullable().optional(),
  bankSwift: z.string().nullable().optional(),
  paymentTermsId: z.number().int().positive().nullable().optional(),
  defaultCurrencyCode: z.string().nullable().optional(),
  taxCodeId: z.number().int().positive().nullable().optional(),
  incotermId: z.number().int().positive().nullable().optional(),
  defaultDepartmentId: z.number().int().positive().nullable().optional(),
  defaultContractId: z.number().int().positive().nullable().optional(),
  defaultCarrierId: z.number().int().positive().nullable().optional(),
  defaultTransportMode: z.string().nullable().optional(),
  billControlPolicy: z.string().nullable().optional(),
  allowCurrencyOverride: z.boolean().optional(),
  requireApprovalForOverride: z.boolean().optional(),
  riskStatus: z.string().nullable().optional(),
  complianceStatus: z.string().nullable().optional(),
  blockedReason: z.string().nullable().optional(),
  insuranceExpiry: z.string().nullable().optional(),
  complianceNotes: z.string().nullable().optional(),
  notes: z.string().nullable().optional(),
});

export type SupplierFormValues = z.infer<typeof supplierFormSchema>;

export const emptySupplierFormValues = (): SupplierFormValues => ({
  name: "",
  supplierCode: "",
  legalName: "",
  supplierType: "goods",
  status: "active",
  registrationNumber: "",
  category: "",
  contactName: "",
  financeContactName: "",
  logisticsContactName: "",
  email: "",
  phone: "",
  address: "",
  billingAddress: "",
  remitToAddress: "",
  pickupSite: "",
  deliverySite: "",
  taxIdentificationNumber: "",
  bankName: "",
  bankAccountNumber: "",
  bankSwift: "",
  paymentTermsId: null,
  defaultCurrencyCode: "",
  taxCodeId: null,
  incotermId: null,
  defaultDepartmentId: null,
  defaultContractId: null,
  defaultCarrierId: null,
  defaultTransportMode: "",
  billControlPolicy: "standard",
  allowCurrencyOverride: false,
  requireApprovalForOverride: true,
  riskStatus: "unknown",
  complianceStatus: "unknown",
  blockedReason: "",
  insuranceExpiry: "",
  complianceNotes: "",
  notes: "",
});
