export type ErpCapabilityStatus = "implemented" | "partial" | "missing" | "disabled" | "degraded";
export type ErpCapability = { id:string; category:string; label:string; status:ErpCapabilityStatus; aliases:readonly string[]; routes:readonly string[]; apis:readonly string[]; permissions:readonly string[]; evidence:readonly string[]; featureFlag:string|null };

const definitions = {
  finance: { implemented:["Accounts Payable","VAT/tax handling","Multi-currency","Financial dashboards and reports","Audit trails"], partial:["General Ledger","Accounts Receivable","Cash flow management","Multi-company / multi-entity consolidation","Budgeting and forecasting"], missing:["Bank reconciliation","Fixed assets","Year-end close support"] },
  procurement: { implemented:["Purchase requisitions","Purchase order creation","PO approvals","Supplier/vendor master data","Purchase contracts","RFQs","Purchase order sending","Goods receipt / GRV","PO-to-invoice matching","Procurement audit trail","Multi-currency purchasing","International order tracking"], partial:["Supplier price lists","Budget or cost-centre approval"], missing:["Purchase returns"] },
  inventory: { implemented:["Item master data","SKU/item codes","Item categories","Item descriptions","Units of measure","On-hand quantity","Allocated/reserved quantity","Available quantity","Reorder points","Min/max levels","Stock valuation","Multi-location stock","Multi-bin stock","Serial number tracking","Lot/batch tracking","Vendor lead times","Stock counts","Stock adjustments","Inventory transfers"], partial:["Expiry tracking","Reorder forecasting"], missing:["Slow-moving stock reports"] },
  warehouse: { implemented:["Receiving","Put-away","Dispatch","Bin management","Warehouse transfers","Stock counts","Mobile barcode scanning","Multi-warehouse visibility"], partial:["Picking","Delivery advice","Warehouse enquiries","Inter-branch transfers","Mobile WMS app"], missing:["Packing","Pick tickets","POD capture"] },
  manufacturing: { implemented:[], partial:[], missing:["Bill of Materials","Work in Progress","MRP/material planning","Production planning","Production scheduling","Shop floor control","Work centres","Machine/labour costing","Kitting/assembly","Disassembly","Batch/process manufacturing","Quality control","Waste reduction","Production documents"] },
  logistics: { implemented:["Shipment creation","Carrier tracking","Delivery notes","Delivery status","ETA tracking","Late delivery alerts","Shipment-to-order links","Inbound/outbound shipment status","Filter by PO number","Filter by supplier","Filter by carrier","Filter by tracking number","Filter by ETA","Filter by status","Filter by risk bucket"], partial:["Dispatch planning","Delivery cost rates"], missing:["Shipment manifests","Proof of delivery","Container item management"] },
  suppliers: { implemented:["Supplier master data","Supplier banking details","Supplier contacts","Supplier performance","Supplier RFQs","PO confirmation","Supplier invoice submission","Document uploads","Supplier payment status","Supplier contracts","Supplier compliance"], partial:["Supplier price lists","Vendor lead times","Supplier risk scoring"], missing:["Supplier communication history"] },
  sales_crm: { implemented:["Quotes"], partial:["Customer master data"], missing:["Sales orders","Sales returns","Customer balances","Credit limits","CRM activities","Sales analysis","Mobile sales app","eCommerce integration","Point of sale","Customer statements","Delivery from sales orders"] },
  projects: { implemented:[], partial:["Cost tracking","Document attachments"], missing:["Project budgets","Project quotes","Project invoicing","Resource scheduling","Labour/machine hours","Project progress","Checklists"] },
  analytics: { implemented:["BI dashboards","Analysis views","Report builder","KPI cards","Drilldowns","Visual charts","Supplier reports","Inventory reports","Procurement reports","AP aging","Operational efficiency metrics","Procurement pipeline dashboard","Inventory health dashboard","AP aging dashboard","Logistics ETA risk dashboard","Exceptions aging dashboard","Supplier performance dashboard","Operations trend dashboard"], partial:["Excel integration","Role-based reports"], missing:["Power BI integration"] },
  controls: { implemented:["User roles","Permissions","Approval workflows","PO approvals","Payment approvals","Audit trails","Document matching","Segregation of duties","Management authorisation","Alerts and notifications"], partial:["Access rights per warehouse/bin"], missing:["Credit approvals"] },
  mobile: { implemented:["Barcode scanning","Mobile approvals","Mobile stock counts"], partial:["Mobile WMS","Mobile inventory enquiries"], missing:["Mobile sales","Sign-on-glass","Mobile requisitions","Mobile job/workshop functions","GPS sales activity tracking"] },
} as const;

const slug=(s:string)=>s.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
const canonicalKey=(label:string)=>({"ap-aging-dashboard":"ap-aging","supplier-performance-dashboard":"supplier-performance"}[slug(label)]??slug(label));
const rawCapabilities: readonly ErpCapability[] = Object.entries(definitions).flatMap(([category,groups]) =>
  (["implemented","partial","missing"] as const).flatMap(status => groups[status].map(label => ({id:`${category}.${slug(label)}`,category,label,status,aliases:[],routes:[],apis:[],permissions:[],evidence:[],featureFlag:null})))
);
const rank:Record<ErpCapabilityStatus,number>={missing:0,partial:1,degraded:1,disabled:1,implemented:2};
const unique=new Map<string,ErpCapability>();
for(const item of rawCapabilities){const key=canonicalKey(item.label);const prior=unique.get(key);if(!prior){unique.set(key,item);continue;}const status=rank[item.status]<rank[prior.status]?item.status:prior.status;unique.set(key,{...prior,status,aliases:[...prior.aliases,item.id]});}
export const erpCapabilityCatalog: readonly ErpCapability[]=[...unique.values()];
export const erpCapabilitySummary = Object.freeze({ rawTotal:rawCapabilities.length, total:erpCapabilityCatalog.length, implemented:erpCapabilityCatalog.filter(x=>x.status==="implemented").length, partial:erpCapabilityCatalog.filter(x=>x.status==="partial").length, missing:erpCapabilityCatalog.filter(x=>x.status==="missing").length });
