#!/usr/bin/env node
import fs from "node:fs";
import net from "node:net";
import { spawn } from "node:child_process";
import { createRequire } from "node:module";
import process from "node:process";
import { parse as parseDotenv } from "dotenv";

const npmCmd = process.platform === "win32" ? "npm.cmd" : "npm";
const envPath = ".env";
const defaultPort = process.env.PORT || "5000";
const defaultDbUrl = "postgresql://postgres:postgres@localhost:5432/inventory_dev?sslmode=disable";
const detached = process.argv.includes("--detach");
const require = createRequire(import.meta.url);

function readEnvFile() {
  if (!fs.existsSync(envPath)) return {};
  return parseDotenv(fs.readFileSync(envPath, "utf8"));
}

function ensureLocalEnv() {
  if (fs.existsSync(envPath)) return false;
  const body = [
    "# Local development defaults generated by npm run local:up",
    "NODE_ENV=development",
    "RUNTIME_DEPLOYMENT=development",
    "HOST=127.0.0.1",
    `PORT=${defaultPort}`,
    `DATABASE_URL=${defaultDbUrl}`,
    "SESSION_SECRET=dev-session-secret-change-me",
    "INTERNAL_EXPORT_TOKEN=dev-internal-export-token-change-me",
    "ALLOW_UNVERIFIED_EMAIL_LOGIN=true",
    "DEV_TEST_LOGIN_ENABLED=true",
    "SKIP_PRODUCT_ONBOARDING=true",
    "ALLOW_SETUP_SKIP=true",
    "AUTO_SEED_ON_EMPTY_DB=true",
    "PGSSLMODE=disable",
    "",
  ].join("\n");
  fs.writeFileSync(envPath, body, "utf8");
  return true;
}

function tcpProbe(host, port, timeoutMs = 750) {
  return new Promise((resolve) => {
    const socket = net.createConnection({ host, port: Number(port) });
    const done = (ok) => {
      socket.destroy();
      resolve(ok);
    };
    socket.setTimeout(timeoutMs);
    socket.once("connect", () => done(true));
    socket.once("timeout", () => done(false));
    socket.once("error", () => done(false));
  });
}

function mergeLocalRuntimeEnv(fileEnv) {
  const configuredDatabaseUrl = process.env.DATABASE_URL || fileEnv.DATABASE_URL;
  const pgUser = process.env.PGUSER || fileEnv.PGUSER;
  const pgPassword = process.env.PGPASSWORD || fileEnv.PGPASSWORD;
  const pgHost = process.env.PGHOST || fileEnv.PGHOST || "127.0.0.1";
  const pgPort = process.env.PGPORT || fileEnv.PGPORT || fileEnv.DB_PORT || "5432";
  const pgDatabase = process.env.PGDATABASE || fileEnv.PGDATABASE;
  const databaseUrl = configuredDatabaseUrl || (pgUser && pgDatabase
    ? `postgresql://${encodeURIComponent(pgUser)}:${encodeURIComponent(pgPassword || "")}@${pgHost}:${pgPort}/${encodeURIComponent(pgDatabase)}?sslmode=disable`
    : defaultDbUrl);
  return {
    ...fileEnv,
    ...process.env,
    NODE_ENV: process.env.NODE_ENV || fileEnv.NODE_ENV || "development",
    RUNTIME_DEPLOYMENT: process.env.RUNTIME_DEPLOYMENT || fileEnv.RUNTIME_DEPLOYMENT || "development",
    HOST: process.env.HOST || fileEnv.HOST || "127.0.0.1",
    PORT: process.env.PORT || fileEnv.PORT || defaultPort,
    DATABASE_URL: databaseUrl,
    SESSION_SECRET: process.env.SESSION_SECRET || fileEnv.SESSION_SECRET || "dev-session-secret-change-me",
    INTERNAL_EXPORT_TOKEN:
      process.env.INTERNAL_EXPORT_TOKEN || fileEnv.INTERNAL_EXPORT_TOKEN || "dev-internal-export-token-change-me",
    ALLOW_UNVERIFIED_EMAIL_LOGIN: process.env.ALLOW_UNVERIFIED_EMAIL_LOGIN || fileEnv.ALLOW_UNVERIFIED_EMAIL_LOGIN || "true",
    DEV_TEST_LOGIN_ENABLED: process.env.DEV_TEST_LOGIN_ENABLED || fileEnv.DEV_TEST_LOGIN_ENABLED || "true",
    SKIP_PRODUCT_ONBOARDING: process.env.SKIP_PRODUCT_ONBOARDING || fileEnv.SKIP_PRODUCT_ONBOARDING || "true",
    ALLOW_SETUP_SKIP: process.env.ALLOW_SETUP_SKIP || fileEnv.ALLOW_SETUP_SKIP || "true",
    AUTO_SEED_ON_EMPTY_DB: process.env.AUTO_SEED_ON_EMPTY_DB || fileEnv.AUTO_SEED_ON_EMPTY_DB || "true",
    PGSSLMODE: process.env.PGSSLMODE || fileEnv.PGSSLMODE || "disable",
  };
}

const createdEnv = ensureLocalEnv();
const fileEnv = readEnvFile();
const runtimeEnv = mergeLocalRuntimeEnv(fileEnv);
const port = runtimeEnv.PORT;
const url = `http://127.0.0.1:${port}`;

fs.writeFileSync(".local-dev-url", `APP_URL=${url}\nPORT=${port}\n`, "utf8");

console.log("ISSSourcing local app runner");
console.log(`URL: ${url}`);
console.log(`Env: ${createdEnv ? "created .env" : "using existing .env"}; dev test login enabled`);
console.log(`DB: ${runtimeEnv.DATABASE_URL.replace(/:\/\/([^:]+):([^@]+)@/, "://$1:***@")}`);

const pgPort = runtimeEnv.DATABASE_URL.match(/:(\d+)\//)?.[1] || "5432";
if (!(await tcpProbe("127.0.0.1", pgPort))) {
  console.warn(`PostgreSQL was not reachable on 127.0.0.1:${pgPort}.`);
  console.warn("The app will still serve startup diagnostics, but login/data tests need PostgreSQL running.");
  console.warn("Quick DB option: docker run --name iss-pg -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=inventory_dev -p 5432:5432 -d postgres:16");
}

const useShell = process.platform === "win32";
const stdoutFd = detached ? fs.openSync(`.local-app-${port}.log`, "a") : undefined;
const stderrFd = detached ? fs.openSync(`.local-app-${port}.error.log`, "a") : undefined;
const launchCommand = detached ? process.execPath : useShell ? "cmd.exe" : npmCmd;
const launchArgs = detached
  ? [require.resolve("tsx/cli"), "server/index.ts"]
  : useShell
    ? ["/d", "/s", "/c", `${npmCmd} run dev`]
    : ["run", "dev"];
const child = spawn(launchCommand, launchArgs, {
  cwd: process.cwd(),
  env: runtimeEnv,
  stdio: detached ? ["ignore", stdoutFd, stderrFd] : "inherit",
  shell: false,
  detached,
});

if (detached) {
  child.unref();
  console.log(`Started detached local server process ${child.pid}.`);
  console.log(`Logs: .local-app-${port}.log and .local-app-${port}.error.log`);
  process.exit(0);
}

function shutdown() {
  child.kill();
  if (process.platform === "win32" && child.pid) {
    spawn("taskkill", ["/pid", String(child.pid), "/t", "/f"], { stdio: "ignore" });
  }
}

process.on("SIGINT", shutdown);
process.on("SIGTERM", shutdown);

child.on("exit", (code, signal) => {
  if (signal) process.exit(0);
  process.exit(code ?? 0);
});
