#!/usr/bin/env node
import fs from "node:fs";
import net from "node:net";
import { spawn } from "node:child_process";
import process from "node:process";

const npmCmd = process.platform === "win32" ? "npm.cmd" : "npm";
const envPath = ".env";
const defaultPort = process.env.PORT || "5000";
const defaultDbUrl = "postgresql://postgres:postgres@localhost:5432/inventory_dev?sslmode=disable";

function readEnvFile() {
  if (!fs.existsSync(envPath)) return {};
  return Object.fromEntries(
    fs
      .readFileSync(envPath, "utf8")
      .split(/\r?\n/)
      .map((line) => line.trim())
      .filter((line) => line && !line.startsWith("#") && line.includes("="))
      .map((line) => {
        const idx = line.indexOf("=");
        return [line.slice(0, idx), line.slice(idx + 1)];
      }),
  );
}

function ensureLocalEnv() {
  if (fs.existsSync(envPath)) return false;
  const body = [
    "# Local development defaults generated by npm run local:up",
    "NODE_ENV=development",
    "RUNTIME_DEPLOYMENT=development",
    "HOST=127.0.0.1",
    `PORT=${defaultPort}`,
    `DATABASE_URL=${defaultDbUrl}`,
    "SESSION_SECRET=dev-session-secret-change-me",
    "INTERNAL_EXPORT_TOKEN=dev-internal-export-token-change-me",
    "ALLOW_UNVERIFIED_EMAIL_LOGIN=true",
    "DEV_TEST_LOGIN_ENABLED=true",
    "SKIP_PRODUCT_ONBOARDING=true",
    "ALLOW_SETUP_SKIP=true",
    "AUTO_SEED_ON_EMPTY_DB=true",
    "PGSSLMODE=disable",
    "",
  ].join("\n");
  fs.writeFileSync(envPath, body, "utf8");
  return true;
}

function tcpProbe(host, port, timeoutMs = 750) {
  return new Promise((resolve) => {
    const socket = net.createConnection({ host, port: Number(port) });
    const done = (ok) => {
      socket.destroy();
      resolve(ok);
    };
    socket.setTimeout(timeoutMs);
    socket.once("connect", () => done(true));
    socket.once("timeout", () => done(false));
    socket.once("error", () => done(false));
  });
}

function mergeLocalRuntimeEnv(fileEnv) {
  return {
    ...process.env,
    NODE_ENV: process.env.NODE_ENV || fileEnv.NODE_ENV || "development",
    RUNTIME_DEPLOYMENT: process.env.RUNTIME_DEPLOYMENT || fileEnv.RUNTIME_DEPLOYMENT || "development",
    HOST: process.env.HOST || fileEnv.HOST || "127.0.0.1",
    PORT: process.env.PORT || fileEnv.PORT || defaultPort,
    DATABASE_URL: process.env.DATABASE_URL || fileEnv.DATABASE_URL || defaultDbUrl,
    SESSION_SECRET: process.env.SESSION_SECRET || fileEnv.SESSION_SECRET || "dev-session-secret-change-me",
    INTERNAL_EXPORT_TOKEN:
      process.env.INTERNAL_EXPORT_TOKEN || fileEnv.INTERNAL_EXPORT_TOKEN || "dev-internal-export-token-change-me",
    ALLOW_UNVERIFIED_EMAIL_LOGIN: process.env.ALLOW_UNVERIFIED_EMAIL_LOGIN || fileEnv.ALLOW_UNVERIFIED_EMAIL_LOGIN || "true",
    DEV_TEST_LOGIN_ENABLED: process.env.DEV_TEST_LOGIN_ENABLED || fileEnv.DEV_TEST_LOGIN_ENABLED || "true",
    SKIP_PRODUCT_ONBOARDING: process.env.SKIP_PRODUCT_ONBOARDING || fileEnv.SKIP_PRODUCT_ONBOARDING || "true",
    ALLOW_SETUP_SKIP: process.env.ALLOW_SETUP_SKIP || fileEnv.ALLOW_SETUP_SKIP || "true",
    AUTO_SEED_ON_EMPTY_DB: process.env.AUTO_SEED_ON_EMPTY_DB || fileEnv.AUTO_SEED_ON_EMPTY_DB || "true",
    PGSSLMODE: process.env.PGSSLMODE || fileEnv.PGSSLMODE || "disable",
  };
}

const createdEnv = ensureLocalEnv();
const fileEnv = readEnvFile();
const runtimeEnv = mergeLocalRuntimeEnv(fileEnv);
const port = runtimeEnv.PORT;
const url = `http://127.0.0.1:${port}`;

fs.writeFileSync(".local-dev-url", `APP_URL=${url}\nPORT=${port}\n`, "utf8");

console.log("InvTrack local app runner");
console.log(`URL: ${url}`);
console.log(`Env: ${createdEnv ? "created .env" : "using existing .env"}; dev test login enabled`);
console.log(`DB: ${runtimeEnv.DATABASE_URL.replace(/:\/\/([^:]+):([^@]+)@/, "://$1:***@")}`);

const pgPort = runtimeEnv.DATABASE_URL.match(/:(\d+)\//)?.[1] || "5432";
if (!(await tcpProbe("127.0.0.1", pgPort))) {
  console.warn(`PostgreSQL was not reachable on 127.0.0.1:${pgPort}.`);
  console.warn("The app will still serve startup diagnostics, but login/data tests need PostgreSQL running.");
  console.warn("Quick DB option: docker run --name iss-pg -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=inventory_dev -p 5432:5432 -d postgres:16");
}

const useShell = process.platform === "win32";
const child = spawn(useShell ? "cmd.exe" : npmCmd, useShell ? ["/d", "/s", "/c", `${npmCmd} run dev`] : ["run", "dev"], {
  cwd: process.cwd(),
  env: runtimeEnv,
  stdio: "inherit",
  shell: false,
});

function shutdown() {
  child.kill();
  if (process.platform === "win32" && child.pid) {
    spawn("taskkill", ["/pid", String(child.pid), "/t", "/f"], { stdio: "ignore" });
  }
}

process.on("SIGINT", shutdown);
process.on("SIGTERM", shutdown);

child.on("exit", (code, signal) => {
  if (signal) process.exit(0);
  process.exit(code ?? 0);
});
