// Document generator service
import type { PDFPage, PDFFont } from 'pdf-lib';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import Excel from 'exceljs';
import { createWriteStream } from 'fs';
import { pipeline } from 'stream';
import { promisify } from 'util';
import type { 
  InventoryItem,
  ReportType,
  ReportFormat} from '@shared/schema';
import { 
  ReorderRequest, 
  User, 
  Supplier, 
  Warehouse, 
  Category, 
  PurchaseOrder, 
  PurchaseRequisition,
  reportTypeEnum,
  reportFormatEnum
} from '@shared/schema';
import { format } from 'date-fns';

const pipelineAsync = promisify(pipeline);

// ——— Shared PDF layout (matches app style: InvTrack, accent blue, clean table) ———
const PDF_LAYOUT = {
  pageWidth: 612,
  pageHeight: 792,
  margin: 50,
  headerTop: 50,
  headerHeight: 72,
  footerHeight: 28,
  tableRowHeight: 16,
  tableHeaderHeight: 20,
  fontSize: 9,
  fontHeaderSize: 10,
  titleSize: 18,
  // App accent (HSL 221 83% 53%) → RGB
  accent: rgb(0.29, 0.45, 0.95),
  accentMuted: rgb(0.85, 0.89, 0.98),
  text: rgb(0.11, 0.18, 0.25),
  muted: rgb(0.45, 0.48, 0.55),
  border: rgb(0.85, 0.87, 0.9),
} as const;

const APP_NAME = 'InvTrack';

function formatPdfCell(value: unknown, opts?: { currency?: boolean; date?: boolean }): string {
  if (value === null || value === undefined) return '—';
  if (opts?.currency) {
    const n = Number(value);
    if (Number.isNaN(n)) return '—';
    return `$${n.toFixed(2)}`;
  }
  if (opts?.date) {
    if (value instanceof Date) return format(value, 'MMM d, yyyy');
    const d = new Date(value as string | number);
    if (!Number.isNaN(d.getTime())) return format(d, 'MMM d, yyyy');
    return String(value);
  }
  if (typeof value === 'number' && Number.isNaN(value)) return '—';
  return String(value);
}

function truncateForPdf(s: string, maxLen: number): string {
  if (s.length <= maxLen) return s;
  return s.slice(0, maxLen - 3) + '…';
}

function drawPdfReportHeader(
  page: PDFPage,
  title: string,
  font: PDFFont,
  boldFont: PDFFont
): void {
  const { width, height } = page.getSize();
  const m = PDF_LAYOUT.margin;
  const y = height - PDF_LAYOUT.headerTop;

  page.drawText(APP_NAME, {
    x: m,
    y,
    size: 12,
    font: boldFont,
    color: PDF_LAYOUT.accent,
  });
  page.drawText(title, {
    x: m,
    y: y - 20,
    size: PDF_LAYOUT.titleSize,
    font: boldFont,
    color: PDF_LAYOUT.text,
  });
  const dateStr = format(new Date(), 'MMMM d, yyyy');
  page.drawText(`Generated on ${dateStr}`, {
    x: m,
    y: y - 42,
    size: PDF_LAYOUT.fontHeaderSize,
    font,
    color: PDF_LAYOUT.muted,
  });
  // Line under header
  page.drawLine({
    start: { x: m, y: y - 52 },
    end: { x: width - m, y: y - 52 },
    thickness: 0.5,
    color: PDF_LAYOUT.border,
  });
}

function drawPdfReportFooter(
  page: PDFPage,
  pageNum: number,
  font: PDFFont,
  totalPages?: number
): void {
  const { width, height } = page.getSize();
  const m = PDF_LAYOUT.margin;
  const y = PDF_LAYOUT.footerHeight;

  // Clear footer band so we can safely redraw after pagination is finalized.
  page.drawRectangle({
    x: m - 2,
    y: y - 2,
    width: width - (m - 2) * 2,
    height: 14,
    color: rgb(1, 1, 1),
  });

  page.drawText(`Generated by ${APP_NAME}`, {
    x: m,
    y,
    size: 8,
    font,
    color: PDF_LAYOUT.muted,
  });
  const pageLabel = totalPages && totalPages > 0 ? `Page ${pageNum} of ${totalPages}` : `Page ${pageNum}`;
  const pageLabelWidth = font.widthOfTextAtSize(pageLabel, 8);
  page.drawText(pageLabel, {
    x: width - m - pageLabelWidth,
    y,
    size: 8,
    font,
    color: PDF_LAYOUT.muted,
  });
}

function drawSummarySection(
  page: PDFPage,
  title: string,
  metrics: Array<{ label: string; value: string }>,
  font: PDFFont,
  boldFont: PDFFont,
): void {
  const m = PDF_LAYOUT.margin;
  const top = PDF_LAYOUT.pageHeight - PDF_LAYOUT.headerHeight - 8;
  page.drawText("Summary", {
    x: m,
    y: top,
    size: 11,
    font: boldFont,
    color: PDF_LAYOUT.text,
  });
  page.drawText(title, {
    x: m + 66,
    y: top,
    size: 9,
    font,
    color: PDF_LAYOUT.muted,
  });
  const cardY = top - 30;
  const totalWidth = PDF_LAYOUT.pageWidth - m * 2;
  const gap = 8;
  const cardWidth = Math.max(80, Math.floor((totalWidth - gap * (metrics.length - 1)) / metrics.length));
  metrics.forEach((metric, index) => {
    const x = m + index * (cardWidth + gap);
    page.drawRectangle({
      x,
      y: cardY - 4,
      width: cardWidth,
      height: 30,
      color: rgb(0.98, 0.99, 1),
      borderColor: PDF_LAYOUT.border,
      borderWidth: 0.5,
    });
    page.drawText(metric.label, {
      x: x + 6,
      y: cardY + 14,
      size: 7,
      font,
      color: PDF_LAYOUT.muted,
    });
    page.drawText(metric.value, {
      x: x + 6,
      y: cardY + 3,
      size: 10,
      font: boldFont,
      color: PDF_LAYOUT.text,
    });
  });
}

/** Draw a bordered table; may add new pages. Uses reportTitle for continuation page headers. */
function drawBorderedTable(
  pdfDoc: PDFDocument,
  pages: PDFPage[],
  reportTitle: string,
  headers: string[],
  colWidths: number[],
  rows: string[][],
  font: PDFFont,
  boldFont: PDFFont,
  tableTopOverride?: number,
): void {
  const m = PDF_LAYOUT.margin;
  const tableTop = tableTopOverride ?? (PDF_LAYOUT.pageHeight - PDF_LAYOUT.headerHeight - PDF_LAYOUT.margin);
  const bottomY = PDF_LAYOUT.margin + PDF_LAYOUT.footerHeight + PDF_LAYOUT.tableRowHeight;
  const rowH = PDF_LAYOUT.tableRowHeight;
  const headerH = PDF_LAYOUT.tableHeaderHeight;
  let pageIndex = 0;
  let y = tableTop - headerH;

  function currentPage(): PDFPage {
    return pages[pageIndex];
  }

  function drawHorizontalLine(page: PDFPage, yLine: number): void {
    page.drawLine({
      start: { x: m, y: yLine },
      end: { x: m + colWidths.reduce((a, b) => a + b, 0), y: yLine },
      thickness: 0.5,
      color: PDF_LAYOUT.border,
    });
  }

  function drawVerticalLines(page: PDFPage, yTop: number, yBottom: number): void {
    let x = m;
    for (let i = 0; i <= colWidths.length; i++) {
      page.drawLine({
        start: { x, y: yTop },
        end: { x, y: yBottom },
        thickness: 0.5,
        color: PDF_LAYOUT.border,
      });
      if (i < colWidths.length) x += colWidths[i];
    }
  }

  // Header row (filled background + text)
  const headerY = tableTop - headerH * 0.5;
  currentPage().drawRectangle({
    x: m,
    y: tableTop - headerH,
    width: colWidths.reduce((a, b) => a + b, 0),
    height: headerH,
    color: PDF_LAYOUT.accentMuted,
  });
  let xPos = m + 4;
  headers.forEach((h, i) => {
    currentPage().drawText(truncateForPdf(h, 24), {
      x: xPos,
      y: headerY,
      size: PDF_LAYOUT.fontHeaderSize,
      font: boldFont,
      color: PDF_LAYOUT.text,
    });
    xPos += colWidths[i];
  });
  drawHorizontalLine(currentPage(), tableTop - headerH);
  drawVerticalLines(currentPage(), tableTop - headerH, tableTop);
  y = tableTop - headerH - rowH;

  for (let r = 0; r < rows.length; r++) {
    if (y < bottomY) {
      pageIndex++;
      if (pageIndex >= pages.length) {
        const newPage = pdfDoc.addPage([PDF_LAYOUT.pageWidth, PDF_LAYOUT.pageHeight]);
        pages.push(newPage);
        drawPdfReportHeader(newPage, reportTitle, font, boldFont);
        drawPdfReportFooter(newPage, pages.length, font);
        y = tableTop - headerH;
        currentPage().drawRectangle({
          x: m,
          y: y,
          width: colWidths.reduce((a, b) => a + b, 0),
          height: headerH,
          color: PDF_LAYOUT.accentMuted,
        });
        xPos = m + 4;
        headers.forEach((h, i) => {
          currentPage().drawText(truncateForPdf(h, 24), {
            x: xPos,
            y: y + headerH * 0.5 - 4,
            size: PDF_LAYOUT.fontHeaderSize,
            font: boldFont,
            color: PDF_LAYOUT.text,
          });
          xPos += colWidths[i];
        });
        drawHorizontalLine(currentPage(), y);
        drawVerticalLines(currentPage(), y, y + headerH);
        y -= rowH;
      }
    }
    const row = rows[r];
    xPos = m + 4;
    row.forEach((cell, i) => {
      currentPage().drawText(truncateForPdf(cell, 28), {
        x: xPos,
        y: y + rowH * 0.5 - 4,
        size: PDF_LAYOUT.fontSize,
        font,
        color: PDF_LAYOUT.text,
      });
      xPos += colWidths[i];
    });
    drawHorizontalLine(currentPage(), y);
    if (r === 0 || y + rowH >= tableTop - headerH) {
      drawVerticalLines(currentPage(), y, y + rowH);
    }
    y -= rowH;
  }
  drawVerticalLines(currentPage(), y + rowH, tableTop);
}

/** Inventory item with optional category name for PDF export */
export type InventoryItemForPdf = InventoryItem & { categoryName?: string };

/**
 * Generate a PDF document from inventory data (shared InvTrack layout, clean data).
 * @param template 'standard' (default) or 'compact' for tighter layout
 */
export async function generateInventoryPdf(
  items: InventoryItemForPdf[],
  title: string,
  _columns?: any[],
  template: PdfTemplate = 'standard'
): Promise<Buffer> {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const page = pdfDoc.addPage([PDF_LAYOUT.pageWidth, PDF_LAYOUT.pageHeight]);
  const pages: PDFPage[] = [page];
  drawPdfReportHeader(page, title, font, boldFont);
  drawPdfReportFooter(page, 1, font);

  const headers = ['SKU', 'Name', 'Category', 'Quantity', 'Price', 'Status'];
  const colWidths = [78, 148, 88, 52, 72, 82];

  const rows = items.map((item) => {
    const qty = Number(item.quantity);
    const threshold = item.lowStockThreshold != null ? Number(item.lowStockThreshold) : null;
    const status =
      !Number.isFinite(qty) || qty <= 0
        ? 'Out of Stock'
        : threshold != null && Number.isFinite(threshold) && qty <= threshold
          ? 'Low Stock'
          : 'In Stock';
    return [
      formatPdfCell(item.sku),
      formatPdfCell(item.name),
      formatPdfCell((item as InventoryItemForPdf).categoryName ?? item.categoryId),
      formatPdfCell(item.quantity),
      formatPdfCell(item.price, { currency: true }),
      status,
    ];
  });

  const lowStockCount = items.filter((item) => {
    const qty = Number(item.quantity ?? 0);
    const threshold = Number(item.lowStockThreshold ?? 0);
    return Number.isFinite(qty) && Number.isFinite(threshold) && qty <= threshold;
  }).length;
  drawSummarySection(
    page,
    "Inventory health snapshot",
    [
      { label: "Total SKUs", value: String(items.length) },
      { label: "Low stock", value: String(lowStockCount) },
      {
        label: "Inventory value",
        value: `$${items.reduce((sum, item) => sum + Number(item.price ?? 0) * Number(item.quantity ?? 0), 0).toFixed(2)}`,
      },
    ],
    font,
    boldFont,
  );

  const tableTop = PDF_LAYOUT.pageHeight - PDF_LAYOUT.headerHeight - PDF_LAYOUT.margin - 56;
  drawBorderedTable(pdfDoc, pages, title, headers, colWidths, rows, font, boldFont, tableTop);
  const totalPages = pages.length;
  pages.forEach((p, index) => drawPdfReportFooter(p, index + 1, font, totalPages));

  const pdfBytes = await pdfDoc.save();
  return Buffer.from(pdfBytes);
}

/** UTF-8 BOM so Excel recognizes encoding */
const CSV_BOM = '\uFEFF';
/** CRLF for Excel-friendly line endings */
const CSV_EOL = '\r\n';

/**
 * Generate a CSV document from inventory data.
 * Uses UTF-8 BOM + sep=, + CRLF so Excel opens as a clean table.
 */
export async function generateInventoryCsv(items: InventoryItem[], title: string, _columns?: any[]): Promise<Buffer> {
  const lines = [CSV_BOM + 'sep=,', ['SKU', 'Name', 'Description', 'Category', 'Quantity', 'Price', 'Cost', 'Status', 'Low Stock Threshold'].join(',')];
  items.forEach(item => {
    const status = item.quantity <= 0 ? 'Out of Stock' : 
                  (item.lowStockThreshold && item.quantity <= item.lowStockThreshold) ? 'Low Stock' : 
                  'In Stock';
    lines.push([
      item.sku || '',
      item.name,
      item.description || '',
      item.categoryId || '',
      item.quantity,
      item.price.toFixed(2),
      item.cost?.toFixed(2) || '',
      status,
      item.lowStockThreshold || ''
    ].map(value => `"${String(value).replace(/"/g, '""')}"`).join(','));
  });
  return Buffer.from(lines.join(CSV_EOL), 'utf8');
}

/**
 * Generate an Excel document from inventory data
 */
export async function generateInventoryExcel(items: InventoryItem[], title: string, _columns?: any[]): Promise<Buffer> {
  // Create a new workbook and add a worksheet
  const workbook = new Excel.Workbook();
  const worksheet = workbook.addWorksheet('Inventory');
  
  // Set up the columns
  worksheet.columns = [
    { header: 'SKU', key: 'sku', width: 15 },
    { header: 'Name', key: 'name', width: 30 },
    { header: 'Description', key: 'description', width: 40 },
    { header: 'Category', key: 'category', width: 15 },
    { header: 'Quantity', key: 'quantity', width: 10 },
    { header: 'Price', key: 'price', width: 12 },
    { header: 'Cost', key: 'cost', width: 12 },
    { header: 'Status', key: 'status', width: 15 },
    { header: 'Low Stock Threshold', key: 'lowStockThreshold', width: 20 },
    { header: 'Last Updated', key: 'lastUpdated', width: 18 }
  ];
  
  // Style the header row
  worksheet.getRow(1).font = { bold: true };
  
  // Add title as a merged cell before the headers
  worksheet.insertRow(1, [title]);
  worksheet.getCell('A1').font = { bold: true, size: 14 };
  worksheet.mergeCells('A1:J1');
  
  // Add data
  items.forEach(item => {
    const status = item.quantity <= 0 ? 'Out of Stock' : 
                  (item.lowStockThreshold && item.quantity <= item.lowStockThreshold) ? 'Low Stock' : 
                  'In Stock';
    
    worksheet.addRow({
      sku: item.sku || '',
      name: item.name,
      description: item.description || '',
      category: item.categoryId || '',
      quantity: item.quantity,
      price: item.price.toFixed(2),
      cost: item.cost?.toFixed(2) || '',
      status: status,
      lowStockThreshold: item.lowStockThreshold || '',
      lastUpdated: item.updatedAt ? format(new Date(item.updatedAt), 'yyyy-MM-dd HH:mm') : ''
    });
  });
  
  // Write to buffer
  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer as ArrayBuffer);
}

/** Hint for formatting a column in generic PDF */
const PDF_COLUMN_FORMAT: Record<string, 'currency' | 'date'> = {
  price: 'currency',
  cost: 'currency',
  totalAmount: 'currency',
  unitPrice: 'currency',
  totalPrice: 'currency',
  orderDate: 'date',
  expectedDeliveryDate: 'date',
  requiredDate: 'date',
  approvalDate: 'date',
  createdAt: 'date',
  updatedAt: 'date',
  timestamp: 'date',
  lastLogin: 'date',
};

/**
 * Generic PDF generator for any data array (shared InvTrack layout, clean data)
 */
export async function generateGenericPdf(data: any[], title: string, columns: {header: string; key: string; width: number}[]): Promise<Buffer> {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const page = pdfDoc.addPage([PDF_LAYOUT.pageWidth, PDF_LAYOUT.pageHeight]);
  const pages: PDFPage[] = [page];
  drawPdfReportHeader(page, title, font, boldFont);
  drawPdfReportFooter(page, 1, font);
  drawSummarySection(
    page,
    "Report metadata",
    [
      { label: "Records", value: String(data.length) },
      { label: "Columns", value: String(columns.length) },
      { label: "Source", value: APP_NAME },
    ],
    font,
    boldFont,
  );

  const headers = columns.map((c) => c.header);
  let colWidths = columns.map((c) => c.width);
  const maxTableWidth = PDF_LAYOUT.pageWidth - 2 * PDF_LAYOUT.margin;
  const totalWidth = colWidths.reduce((a, b) => a + b, 0);
  if (totalWidth > maxTableWidth) {
    const scale = maxTableWidth / totalWidth;
    colWidths = colWidths.map((w) => Math.max(20, Math.round(w * scale)));
  }

  const rows = data.map((item) =>
    columns.map((col) => {
      const raw = item[col.key];
      const fmt = PDF_COLUMN_FORMAT[col.key];
      return formatPdfCell(raw, fmt === 'currency' ? { currency: true } : fmt === 'date' ? { date: true } : undefined);
    })
  );

  const tableTop = PDF_LAYOUT.pageHeight - PDF_LAYOUT.headerHeight - PDF_LAYOUT.margin - 56;
  drawBorderedTable(pdfDoc, pages, title, headers, colWidths, rows, font, boldFont, tableTop);
  const totalPages = pages.length;
  pages.forEach((p, index) => drawPdfReportFooter(p, index + 1, font, totalPages));

  const pdfBytes = await pdfDoc.save();
  return Buffer.from(pdfBytes);
}

/**
 * Generic CSV generator for any data array.
 * Uses UTF-8 BOM + sep=, + CRLF so Excel opens as a clean table.
 */
export async function generateGenericCsv(data: any[], title: string, columns: {header: string; key: string}[]): Promise<Buffer> {
  const lines = [CSV_BOM + 'sep=,', columns.map(col => `"${String(col.header).replace(/"/g, '""')}"`).join(',')];
  data.forEach(item => {
    lines.push(columns.map(col => {
      let value = item[col.key] !== undefined && item[col.key] !== null ? item[col.key] : '';
      if (value instanceof Date) value = format(value, 'yyyy-MM-dd HH:mm');
      return `"${String(value).replace(/"/g, '""')}"`;
    }).join(','));
  });
  return Buffer.from(lines.join(CSV_EOL), 'utf8');
}

/**
 * Generic Excel generator for any data array
 */
export async function generateGenericExcel(data: any[], title: string, columns: {header: string; key: string; width: number}[]): Promise<Buffer> {
  // Create a new workbook and add a worksheet
  const workbook = new Excel.Workbook();
  const worksheet = workbook.addWorksheet(title.substring(0, 31));
  
  // Set up the columns
  worksheet.columns = columns;
  worksheet.getRow(1).font = { bold: true };
  worksheet.insertRow(1, [title]);
  worksheet.getCell('A1').font = { bold: true, size: 14 };
  worksheet.mergeCells(`A1:${String.fromCharCode(64 + columns.length)}1`);
  // Freeze header row (row 2) so it stays visible when scrolling
  worksheet.views = [{ state: "frozen", ySplit: 2, activeCell: "A3" }];
  worksheet.getRow(2).font = { bold: true };

  // Add data
  data.forEach(item => {
    const row: any = {};
    
    columns.forEach(col => {
      let value = item[col.key];
      
      // Handle special cases
      if (value instanceof Date) {
        value = format(value, 'yyyy-MM-dd HH:mm');
      } else if (value === null || value === undefined) {
        value = '';
      }
      
      row[col.key] = value;
    });
    
    worksheet.addRow(row);
  });
  
  // Write to buffer
  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer as ArrayBuffer);
}

/**
 * Create a document generator instance for a specific report type
 */
export function createDocumentGenerator(reportType: ReportType) {
  // Handle inventory-specific reports
  switch (reportType) {
    case 'inventory':
      return {
        pdf: generateInventoryPdf,
        csv: generateInventoryCsv,
        excel: generateInventoryExcel
      };
    
    // For other reports, return generic handlers
    default:
      return {
        pdf: generateGenericPdf,
        csv: generateGenericCsv,
        excel: generateGenericExcel
      };
  }
}

/**
 * Get column definitions for each report type
 */
export function getReportColumns(reportType: ReportType) {
  switch (reportType) {
    case 'inventory':
      return [
        { header: 'SKU', key: 'sku', width: 15 },
        { header: 'Name', key: 'name', width: 30 },
        { header: 'Description', key: 'description', width: 40 },
        { header: 'Category', key: 'categoryId', width: 15 },
        { header: 'Quantity', key: 'quantity', width: 10 },
        { header: 'Price', key: 'price', width: 12 },
        { header: 'Cost', key: 'cost', width: 12 },
        { header: 'Status', key: 'status', width: 15 },
        { header: 'Low Stock Threshold', key: 'lowStockThreshold', width: 20 }
      ];

    case 'categories':
      return [
        { header: 'ID', key: 'id', width: 10 },
        { header: 'Name', key: 'name', width: 30 },
        { header: 'Description', key: 'description', width: 50 }
      ];

    case 'suppliers':
      return [
        { header: 'ID', key: 'id', width: 10 },
        { header: 'Name', key: 'name', width: 30 },
        { header: 'Contact Name', key: 'contactName', width: 30 },
        { header: 'Email', key: 'email', width: 30 },
        { header: 'Phone', key: 'phone', width: 20 },
        { header: 'Address', key: 'address', width: 50 }
      ];

    case 'warehouses':
      return [
        { header: 'ID', key: 'id', width: 10 },
        { header: 'Name', key: 'name', width: 30 },
        { header: 'Location', key: 'location', width: 30 },
        { header: 'Contact Person', key: 'contactPerson', width: 30 },
        { header: 'Contact Phone', key: 'contactPhone', width: 20 },
        { header: 'Address', key: 'address', width: 50 },
        { header: 'Is Default', key: 'isDefault', width: 15 }
      ];

    case 'reorder_requests':
      return [
        { header: 'ID', key: 'id', width: 10 },
        { header: 'Request Number', key: 'requestNumber', width: 20 },
        { header: 'Item', key: 'itemName', width: 30 },
        { header: 'Quantity', key: 'quantity', width: 15 },
        { header: 'Status', key: 'status', width: 20 },
        { header: 'Requested By', key: 'requestorName', width: 30 },
        { header: 'Supplier', key: 'supplierName', width: 30 },
        { header: 'Warehouse', key: 'warehouseName', width: 30 },
        { header: 'Date Requested', key: 'createdAt', width: 20 }
      ];

    case 'purchase_orders':
      return [
        { header: 'ID', key: 'id', width: 10 },
        { header: 'Order Number', key: 'orderNumber', width: 20 },
        { header: 'Supplier', key: 'supplierName', width: 30 },
        { header: 'Status', key: 'status', width: 20 },
        { header: 'Order Date', key: 'orderDate', width: 20 },
        { header: 'Expected Delivery', key: 'expectedDeliveryDate', width: 20 },
        { header: 'Total Amount', key: 'totalAmount', width: 15 },
        { header: 'Payment Status', key: 'paymentStatus', width: 20 }
      ];

    case 'purchase_requisitions':
      return [
        { header: 'ID', key: 'id', width: 10 },
        { header: 'Requisition Number', key: 'requisitionNumber', width: 20 },
        { header: 'Requestor', key: 'requestorName', width: 30 },
        { header: 'Status', key: 'status', width: 20 },
        { header: 'Required Date', key: 'requiredDate', width: 20 },
        { header: 'Supplier', key: 'supplierName', width: 30 },
        { header: 'Total Amount', key: 'totalAmount', width: 15 },
        { header: 'Approval Date', key: 'approvalDate', width: 20 }
      ];

    case 'users':
      return [
        { header: 'ID', key: 'id', width: 10 },
        { header: 'Username', key: 'username', width: 20 },
        { header: 'Full Name', key: 'fullName', width: 30 },
        { header: 'Email', key: 'email', width: 30 },
        { header: 'Role', key: 'role', width: 20 },
        { header: 'Active', key: 'active', width: 10 },
        { header: 'Last Login', key: 'lastLogin', width: 20 }
      ];

    case 'stock_movements':
      return [
        { header: 'ID', key: 'id', width: 10 },
        { header: 'Date', key: 'createdAt', width: 20 },
        { header: 'Item', key: 'itemName', width: 30 },
        { header: 'From Warehouse', key: 'fromWarehouseName', width: 25 },
        { header: 'To Warehouse', key: 'toWarehouseName', width: 25 },
        { header: 'Quantity', key: 'quantity', width: 15 },
        { header: 'Type', key: 'movementType', width: 20 },
        { header: 'Reference', key: 'reference', width: 20 },
        { header: 'User', key: 'userName', width: 20 }
      ];

    case 'activity_logs':
      return [
        { header: 'ID', key: 'id', width: 10 },
        { header: 'Timestamp', key: 'timestamp', width: 20 },
        { header: 'User', key: 'userName', width: 20 },
        { header: 'Action', key: 'action', width: 20 },
        { header: 'Description', key: 'description', width: 50 },
        { header: 'Reference Type', key: 'referenceType', width: 20 },
        { header: 'Reference ID', key: 'referenceId', width: 15 }
      ];

    default:
      return [
        { header: 'ID', key: 'id', width: 10 },
        { header: 'Name', key: 'name', width: 30 },
        { header: 'Description', key: 'description', width: 50 }
      ];
  }
}

export type PdfTemplate = 'standard' | 'compact' | 'custom';

export interface GenerateDocumentOptions {
  pdfTemplate?: PdfTemplate;
  /** When pdfTemplate is 'custom', use this buffer as cover/template (its pages are prepended to the report). */
  customTemplateBuffer?: Buffer;
}

/**
 * Merge a custom template PDF (e.g. cover page) with the generated report PDF.
 * Template pages come first, then report pages. Uses pdf-lib.
 */
export async function mergePdfWithTemplate(templateBuffer: Buffer, reportBuffer: Buffer): Promise<Buffer> {
  const templateDoc = await PDFDocument.load(templateBuffer);
  const reportDoc = await PDFDocument.load(reportBuffer);
  const templatePages = templateDoc.getPages();
  const reportPages = reportDoc.getPages();
  const merged = await PDFDocument.create();
  for (let i = 0; i < templatePages.length; i++) {
    const [copied] = await merged.copyPages(templateDoc, [i]);
    merged.addPage(copied);
  }
  for (let i = 0; i < reportPages.length; i++) {
    const [copied] = await merged.copyPages(reportDoc, [i]);
    merged.addPage(copied);
  }
  return Buffer.from(await merged.save());
}

/**
 * Generate document based on report type, format, and data.
 * For PDF, options.pdfTemplate selects layout: standard (default), compact, or custom.
 * When custom, options.customTemplateBuffer pages are prepended to the report.
 */
export async function generateDocument(
  reportType: ReportType,
  format: ReportFormat,
  data: any[],
  title: string,
  options?: GenerateDocumentOptions
): Promise<Buffer> {
  const generator = createDocumentGenerator(reportType);
  const columns = getReportColumns(reportType);
  const pdfTemplate = options?.pdfTemplate === 'custom' ? 'standard' : (options?.pdfTemplate ?? 'standard');

  try {
    if (format === 'pdf') {
      let reportBuffer = await generator.pdf(data, title, columns, pdfTemplate as 'standard' | 'compact');
      if (options?.pdfTemplate === 'custom' && options?.customTemplateBuffer?.length) {
        reportBuffer = await mergePdfWithTemplate(options.customTemplateBuffer, reportBuffer);
      }
      return reportBuffer;
    } else if (format === 'csv') {
      if (reportType === 'inventory') {
        return generator.csv(data, title, columns);
      } else {
        return generator.csv(data, title, columns);
      }
    } else if (format === 'excel') {
      if (reportType === 'inventory') {
        return generator.excel(data, title, columns);
      } else {
        return generator.excel(data, title, columns);
      }
    } else {
      throw new Error(`Unsupported format: ${format}`);
    }
  } catch (error) {
    console.error(`Error generating ${format} document for ${reportType}:`, error);
    throw error;
  }
}